#
# DO NOT MODIFY!!!!
# This file is automatically generated by racc 1.4.5
# from racc grammer file "mediawikiparser.y".
#

require 'racc/parser'


require 'mediacloth/mediawikiast'


class MediaWikiParser < Racc::Parser

module_eval <<'..end mediawikiparser.y modeval..id87c5337b77', 'mediawikiparser.y', 517

attr_accessor :lexer

def initialize
    @nodes = []
    super
end

#Tokenizes input string and parses it.
def parse(input)
    @yydebug=true
    lexer.tokenize(input)
    do_parse
    return @nodes.last
end

#Asks the lexer to return the next token.
def next_token
    return @lexer.lex
end
..end mediawikiparser.y modeval..id87c5337b77

##### racc 1.4.5 generates ###

racc_reduce_table = [
 0, 0, :racc_error,
 1, 54, :_reduce_1,
 1, 56, :_reduce_2,
 1, 56, :_reduce_3,
 1, 56, :_reduce_4,
 1, 56, :_reduce_5,
 1, 56, :_reduce_6,
 1, 56, :_reduce_7,
 1, 56, :_reduce_8,
 1, 56, :_reduce_9,
 1, 56, :_reduce_10,
 3, 56, :_reduce_11,
 3, 56, :_reduce_12,
 6, 56, :_reduce_13,
 4, 56, :_reduce_14,
 5, 56, :_reduce_15,
 6, 56, :_reduce_16,
 1, 56, :_reduce_none,
 0, 65, :_reduce_18,
 1, 65, :_reduce_19,
 3, 63, :_reduce_20,
 4, 63, :_reduce_21,
 0, 71, :_reduce_22,
 2, 71, :_reduce_23,
 3, 71, :_reduce_24,
 1, 66, :_reduce_25,
 3, 66, :_reduce_26,
 1, 72, :_reduce_27,
 3, 72, :_reduce_28,
 0, 68, :_reduce_29,
 2, 68, :_reduce_30,
 0, 69, :_reduce_31,
 2, 69, :_reduce_32,
 0, 67, :_reduce_33,
 2, 67, :_reduce_34,
 3, 67, :_reduce_35,
 1, 55, :_reduce_36,
 2, 55, :_reduce_37,
 1, 57, :_reduce_38,
 1, 57, :_reduce_39,
 3, 70, :_reduce_40,
 4, 70, :_reduce_41,
 0, 75, :_reduce_42,
 4, 75, :_reduce_43,
 5, 75, :_reduce_44,
 0, 76, :_reduce_45,
 3, 76, :_reduce_46,
 4, 76, :_reduce_47,
 3, 76, :_reduce_48,
 4, 76, :_reduce_49,
 1, 73, :_reduce_50,
 1, 73, :_reduce_51,
 1, 73, :_reduce_52,
 1, 73, :_reduce_53,
 1, 73, :_reduce_54,
 1, 73, :_reduce_55,
 2, 74, :_reduce_56,
 2, 74, :_reduce_57,
 3, 74, :_reduce_58,
 3, 74, :_reduce_59,
 4, 58, :_reduce_60,
 4, 59, :_reduce_61,
 0, 79, :_reduce_62,
 3, 78, :_reduce_63,
 0, 78, :_reduce_64,
 2, 77, :_reduce_65,
 3, 77, :_reduce_66,
 4, 60, :_reduce_67,
 3, 60, :_reduce_68,
 2, 80, :_reduce_69,
 3, 80, :_reduce_70,
 2, 81, :_reduce_71,
 0, 81, :_reduce_72,
 2, 82, :_reduce_73,
 3, 82, :_reduce_74,
 3, 61, :_reduce_75,
 3, 62, :_reduce_76,
 3, 64, :_reduce_77,
 1, 83, :_reduce_78,
 2, 83, :_reduce_79,
 2, 83, :_reduce_80,
 3, 83, :_reduce_81 ]

racc_reduce_n = 82

racc_shift_n = 151

racc_action_table = [
    63,     5,     9,    54,    15,    48,    23,   122,    87,    33,
    89,    62,    88,     7,   104,    16,    20,    40,    25,    30,
    32,     1,     4,    87,     8,    89,    14,    87,    83,    89,
    29,    87,    87,    89,    89,    57,    11,    58,    99,   101,
    26,    44,    76,    81,    56,    44,   109,   110,    17,    19,
    64,     5,     9,    19,    15,    87,    23,    89,    80,    33,
   113,    19,   102,     7,   -64,    16,    20,   119,    25,    30,
    32,     1,     4,    98,     8,   -64,    14,   103,   123,    66,
    29,   125,   126,    65,   -62,    58,    11,    96,     5,     9,
    26,    15,    58,    23,   133,    53,    33,    84,    17,    19,
     7,    56,    16,    20,    99,    25,    30,    32,     1,     4,
    40,     8,   138,    14,   140,   141,    44,    29,    56,    56,
    86,   146,    40,    11,   149,   127,   nil,    26,   nil,     5,
     9,   nil,    15,   nil,    23,    17,    19,    33,   nil,   138,
   nil,     7,   nil,    16,    20,   nil,    25,    30,    32,     1,
     4,   nil,     8,   nil,    14,   nil,   nil,   nil,    29,   nil,
   nil,   nil,   nil,   nil,    11,   nil,   nil,   nil,    26,   nil,
     5,     9,    42,    15,   nil,    23,    17,    19,    33,   nil,
   nil,   nil,     7,   nil,    16,    20,   nil,    25,    30,    32,
     1,     4,   nil,     8,   nil,    14,   nil,   nil,   nil,    29,
   nil,   nil,   nil,   nil,   nil,    11,   nil,     5,     9,    26,
    15,   nil,    23,   nil,   nil,    33,   nil,    17,    19,     7,
   nil,    16,    20,   nil,    25,    30,    32,     1,     4,   nil,
     8,   nil,    14,   nil,   nil,   nil,    29,   nil,   nil,   nil,
   nil,   nil,    11,   nil,     5,     9,    26,    15,   nil,    23,
   nil,   nil,    33,   nil,    17,    19,     7,   nil,    16,    20,
   nil,    25,    30,    32,     1,     4,   nil,     8,   nil,    14,
   nil,   nil,   nil,    29,   nil,   nil,   nil,   nil,   nil,    11,
   nil,     5,     9,    26,    15,    47,    23,   nil,   nil,    33,
   nil,    17,    19,     7,   nil,    16,    20,   nil,    25,    30,
    32,     1,     4,   nil,     8,   nil,    14,   nil,   nil,   nil,
    29,   nil,   nil,   nil,   nil,   nil,    11,   nil,     5,     9,
    26,    15,   nil,    23,   nil,   nil,    33,   nil,    17,    19,
     7,   nil,    16,    20,   nil,    25,    30,    32,     1,     4,
   nil,     8,   nil,    14,   nil,   nil,   nil,    29,   nil,   nil,
   nil,   nil,   nil,    11,   nil,     5,     9,    26,    15,   nil,
    23,   nil,   nil,    33,   nil,    17,    19,     7,   nil,    16,
    20,   nil,    25,    30,    32,     1,     4,   nil,     8,   nil,
    14,   nil,   nil,   nil,    29,   nil,   nil,   nil,   nil,   nil,
    11,   nil,     5,     9,    26,    15,   nil,    23,   nil,   nil,
    33,   134,    17,    19,     7,   nil,    16,    20,   nil,    25,
    30,    32,     1,     4,   nil,     8,   nil,    14,   nil,   nil,
   nil,    29,   nil,   nil,   nil,   nil,   nil,    11,   nil,   nil,
   nil,    26,   nil,   nil,   nil,   nil,   131,   nil,   nil,    17,
    19,     5,     9,   nil,    15,   nil,    23,   nil,   130,    33,
   nil,   nil,   nil,     7,   nil,    16,    20,   nil,    25,    30,
    32,     1,     4,   nil,     8,   nil,    14,   nil,   nil,   nil,
    29,   nil,   nil,   nil,   nil,   nil,    11,   nil,     5,     9,
    26,    15,   nil,    23,   nil,   nil,    33,   nil,    17,    19,
     7,   nil,    16,    20,   nil,    25,    30,    32,     1,     4,
   nil,     8,   nil,    14,   nil,   nil,   nil,    29,   nil,   nil,
   nil,   nil,   nil,    11,   nil,     5,     9,    26,    15,   nil,
    23,   nil,   nil,    33,   nil,    17,    19,     7,   nil,    16,
    20,   nil,    25,    30,    32,     1,     4,   nil,     8,   nil,
    14,   nil,   nil,   nil,    29,   nil,   nil,    92,   nil,   nil,
    11,   nil,     5,     9,    26,    15,   nil,    23,   nil,   nil,
    33,   nil,    17,    19,     7,   nil,    16,    20,   nil,    25,
    30,    32,     1,     4,   nil,     8,   nil,    14,   nil,   nil,
   nil,    29,   nil,   nil,   nil,   nil,   nil,    11,   nil,     5,
     9,    26,    15,   nil,    23,   nil,   nil,    33,   nil,    17,
    19,     7,   nil,    16,    20,   nil,    25,    30,    32,     1,
     4,   nil,     8,   nil,    14,   nil,   nil,   nil,    29,   nil,
   nil,   nil,   nil,   nil,    11,   nil,     5,     9,    26,    15,
   nil,    23,   nil,   nil,    33,   nil,    17,    19,     7,    67,
    16,    20,   nil,    25,    30,    32,     1,     4,   nil,     8,
   nil,    14,   nil,   nil,   nil,    29,   nil,   nil,   nil,   nil,
   nil,    11,   nil,     5,     9,    26,    15,   nil,    23,   nil,
   nil,    33,   nil,    17,    19,     7,   nil,    16,    20,   nil,
    25,    30,    32,     1,     4,   nil,     8,   nil,    14,   nil,
   nil,   nil,    29,   nil,   nil,   nil,   nil,   121,    11,   nil,
     5,     9,    26,    15,   nil,    23,   nil,   nil,    33,   nil,
    17,    19,     7,   nil,    16,    20,   nil,    25,    30,    32,
     1,     4,   nil,     8,   nil,    14,   nil,   nil,    71,    29,
   nil,   nil,   nil,   nil,   nil,    11,   nil,   nil,   nil,    26,
   nil,     5,     9,    72,    15,   nil,    23,    17,    19,    33,
   nil,   nil,   nil,     7,   nil,    16,    20,   nil,    25,    30,
    32,     1,     4,   nil,     8,   nil,    14,   nil,   nil,   nil,
    29,   nil,   nil,   nil,   nil,   nil,    11,   nil,     5,     9,
    26,    15,   nil,    23,   nil,   nil,    33,   nil,    17,    19,
     7,   nil,    16,    20,   nil,    25,    30,    32,     1,     4,
   nil,     8,   nil,    14,   nil,   nil,   nil,    29,   nil,   nil,
   nil,   nil,   nil,    11,    74,     5,     9,    26,    15,   nil,
    23,   nil,   nil,    33,   nil,    17,    19,     7,   nil,    16,
    20,   nil,    25,    30,    32,     1,     4,   nil,     8,   nil,
    14,   nil,   nil,   nil,    29,   nil,   nil,   120,   nil,   nil,
    11,   nil,     5,     9,    26,    15,   nil,    23,   nil,   nil,
    33,   nil,    17,    19,     7,   nil,    16,    20,   nil,    25,
    30,    32,     1,     4,   nil,     8,   nil,    14,   nil,   nil,
   nil,    29,   nil,   nil,   nil,   nil,   nil,    11,   nil,     5,
     9,    26,    15,    78,    23,   nil,   nil,    33,   118,    17,
    19,     7,   nil,    16,    20,   nil,    25,    30,    32,     1,
     4,   nil,     8,   nil,    14,   nil,   nil,   nil,    29,   nil,
   nil,   nil,   nil,   nil,    11,   nil,     5,     9,    26,    15,
   nil,    23,   nil,   nil,    33,   nil,    17,    19,     7,   nil,
    16,    20,   nil,    25,    30,    32,     1,     4,   nil,     8,
   nil,    14,   nil,   nil,   nil,    29,   nil,   nil,   nil,   nil,
   nil,    11,   nil,     5,     9,    26,    15,   nil,    23,   nil,
   115,    33,   nil,    17,    19,     7,   nil,    16,    20,   nil,
    25,    30,    32,     1,     4,   nil,     8,   nil,    14,   nil,
   nil,   nil,    29,   nil,   nil,   nil,   nil,   nil,    11,   nil,
     5,     9,    26,    15,   nil,    23,   nil,   nil,    33,   nil,
    17,    19,     7,   nil,    16,    20,   nil,    25,    30,    32,
     1,     4,   nil,     8,   nil,    14,   nil,   nil,   nil,    29,
   nil,   nil,   nil,   nil,   nil,    11,   107,     5,     9,    26,
    15,   nil,    23,   nil,   nil,    33,   nil,    17,    19,     7,
   nil,    16,    20,    82,    25,    30,    32,     1,     4,   nil,
     8,   nil,    14,   nil,   nil,   nil,    29,   nil,   nil,   nil,
   nil,   nil,    11,   nil,     5,     9,    26,    15,   nil,    23,
   nil,   nil,    33,   nil,    17,    19,     7,   nil,    16,    20,
   nil,    25,    30,    32,     1,     4,   nil,     8,   nil,    14,
   nil,   nil,   106,    29,   nil,   nil,   nil,   nil,   nil,    11,
   nil,     5,     9,    26,    15,   nil,    23,   nil,   nil,    33,
   nil,    17,    19,     7,   nil,    16,    20,   nil,    25,    30,
    32,     1,     4,   nil,     8,   nil,    14,   nil,   nil,   nil,
    29,   nil,   nil,   nil,   nil,    94,    11,   nil,   nil,   nil,
    26,   nil,     5,     9,   nil,    15,   nil,    23,    17,    19,
    33,   nil,   138,   nil,     7,   nil,    16,    20,   nil,    25,
    30,    32,     1,     4,   nil,     8,   nil,    14,   nil,   nil,
   nil,    29,   nil,   nil,   nil,   nil,   nil,    11,   nil,   nil,
   nil,    26,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    17,
    19 ]

racc_action_check = [
    33,    36,    36,    26,    36,    19,    36,    95,   131,    36,
   131,    33,    56,    36,    68,    36,    36,    69,    36,    36,
    36,    36,    36,   118,    36,   118,    36,   115,    52,   115,
    36,   134,    88,   134,    88,    29,    36,    29,    63,    63,
    36,    44,    44,    50,    26,    76,    77,    79,    36,    36,
    33,     4,     4,    19,     4,    56,     4,    56,    49,     4,
    85,    48,    64,     4,    45,     4,     4,    90,     4,     4,
     4,     4,     4,    62,     4,    39,     4,    65,    98,    37,
     4,   100,   101,    34,   105,    61,     4,    60,     7,     7,
     4,     7,    59,     7,   116,    23,     7,    53,     4,     4,
     7,   119,     7,     7,   123,     7,     7,     7,     7,     7,
    14,     7,   126,     7,   127,   128,    11,     7,    54,   133,
    55,   137,     8,     7,   139,   102,   nil,     7,   nil,   138,
   138,   nil,   138,   nil,   138,     7,     7,   138,   nil,   138,
   nil,   138,   nil,   138,   138,   nil,   138,   138,   138,   138,
   138,   nil,   138,   nil,   138,   nil,   nil,   nil,   138,   nil,
   nil,   nil,   nil,   nil,   138,   nil,   nil,   nil,   138,   nil,
     9,     9,     9,     9,   nil,     9,   138,   138,     9,   nil,
   nil,   nil,     9,   nil,     9,     9,   nil,     9,     9,     9,
     9,     9,   nil,     9,   nil,     9,   nil,   nil,   nil,     9,
   nil,   nil,   nil,   nil,   nil,     9,   nil,   130,   130,     9,
   130,   nil,   130,   nil,   nil,   130,   nil,     9,     9,   130,
   nil,   130,   130,   nil,   130,   130,   130,   130,   130,   nil,
   130,   nil,   130,   nil,   nil,   nil,   130,   nil,   nil,   nil,
   nil,   nil,   130,   nil,   124,   124,   130,   124,   nil,   124,
   nil,   nil,   124,   nil,   130,   130,   124,   nil,   124,   124,
   nil,   124,   124,   124,   124,   124,   nil,   124,   nil,   124,
   nil,   nil,   nil,   124,   nil,   nil,   nil,   nil,   nil,   124,
   nil,    15,    15,   124,    15,    15,    15,   nil,   nil,    15,
   nil,   124,   124,    15,   nil,    15,    15,   nil,    15,    15,
    15,    15,    15,   nil,    15,   nil,    15,   nil,   nil,   nil,
    15,   nil,   nil,   nil,   nil,   nil,    15,   nil,    20,    20,
    15,    20,   nil,    20,   nil,   nil,    20,   nil,    15,    15,
    20,   nil,    20,    20,   nil,    20,    20,    20,    20,    20,
   nil,    20,   nil,    20,   nil,   nil,   nil,    20,   nil,   nil,
   nil,   nil,   nil,    20,   nil,   117,   117,    20,   117,   nil,
   117,   nil,   nil,   117,   nil,    20,    20,   117,   nil,   117,
   117,   nil,   117,   117,   117,   117,   117,   nil,   117,   nil,
   117,   nil,   nil,   nil,   117,   nil,   nil,   nil,   nil,   nil,
   117,   nil,   114,   114,   117,   114,   nil,   114,   nil,   nil,
   114,   117,   117,   117,   114,   nil,   114,   114,   nil,   114,
   114,   114,   114,   114,   nil,   114,   nil,   114,   nil,   nil,
   nil,   114,   nil,   nil,   nil,   nil,   nil,   114,   nil,   nil,
   nil,   114,   nil,   nil,   nil,   nil,   114,   nil,   nil,   114,
   114,   111,   111,   nil,   111,   nil,   111,   nil,   111,   111,
   nil,   nil,   nil,   111,   nil,   111,   111,   nil,   111,   111,
   111,   111,   111,   nil,   111,   nil,   111,   nil,   nil,   nil,
   111,   nil,   nil,   nil,   nil,   nil,   111,   nil,     0,     0,
   111,     0,   nil,     0,   nil,   nil,     0,   nil,   111,   111,
     0,   nil,     0,     0,   nil,     0,     0,     0,     0,     0,
   nil,     0,   nil,     0,   nil,   nil,   nil,     0,   nil,   nil,
   nil,   nil,   nil,     0,   nil,    57,    57,     0,    57,   nil,
    57,   nil,   nil,    57,   nil,     0,     0,    57,   nil,    57,
    57,   nil,    57,    57,    57,    57,    57,   nil,    57,   nil,
    57,   nil,   nil,   nil,    57,   nil,   nil,    57,   nil,   nil,
    57,   nil,     2,     2,    57,     2,   nil,     2,   nil,   nil,
     2,   nil,    57,    57,     2,   nil,     2,     2,   nil,     2,
     2,     2,     2,     2,   nil,     2,   nil,     2,   nil,   nil,
   nil,     2,   nil,   nil,   nil,   nil,   nil,     2,   nil,    99,
    99,     2,    99,   nil,    99,   nil,   nil,    99,   nil,     2,
     2,    99,   nil,    99,    99,   nil,    99,    99,    99,    99,
    99,   nil,    99,   nil,    99,   nil,   nil,   nil,    99,   nil,
   nil,   nil,   nil,   nil,    99,   nil,    38,    38,    99,    38,
   nil,    38,   nil,   nil,    38,   nil,    99,    99,    38,    38,
    38,    38,   nil,    38,    38,    38,    38,    38,   nil,    38,
   nil,    38,   nil,   nil,   nil,    38,   nil,   nil,   nil,   nil,
   nil,    38,   nil,    93,    93,    38,    93,   nil,    93,   nil,
   nil,    93,   nil,    38,    38,    93,   nil,    93,    93,   nil,
    93,    93,    93,    93,    93,   nil,    93,   nil,    93,   nil,
   nil,   nil,    93,   nil,   nil,   nil,   nil,    93,    93,   nil,
    40,    40,    93,    40,   nil,    40,   nil,   nil,    40,   nil,
    93,    93,    40,   nil,    40,    40,   nil,    40,    40,    40,
    40,    40,   nil,    40,   nil,    40,   nil,   nil,    40,    40,
   nil,   nil,   nil,   nil,   nil,    40,   nil,   nil,   nil,    40,
   nil,    41,    41,    41,    41,   nil,    41,    40,    40,    41,
   nil,   nil,   nil,    41,   nil,    41,    41,   nil,    41,    41,
    41,    41,    41,   nil,    41,   nil,    41,   nil,   nil,   nil,
    41,   nil,   nil,   nil,   nil,   nil,    41,   nil,    43,    43,
    41,    43,   nil,    43,   nil,   nil,    43,   nil,    41,    41,
    43,   nil,    43,    43,   nil,    43,    43,    43,    43,    43,
   nil,    43,   nil,    43,   nil,   nil,   nil,    43,   nil,   nil,
   nil,   nil,   nil,    43,    43,    91,    91,    43,    91,   nil,
    91,   nil,   nil,    91,   nil,    43,    43,    91,   nil,    91,
    91,   nil,    91,    91,    91,    91,    91,   nil,    91,   nil,
    91,   nil,   nil,   nil,    91,   nil,   nil,    91,   nil,   nil,
    91,   nil,    89,    89,    91,    89,   nil,    89,   nil,   nil,
    89,   nil,    91,    91,    89,   nil,    89,    89,   nil,    89,
    89,    89,    89,    89,   nil,    89,   nil,    89,   nil,   nil,
   nil,    89,   nil,   nil,   nil,   nil,   nil,    89,   nil,    46,
    46,    89,    46,    46,    46,   nil,   nil,    46,    89,    89,
    89,    46,   nil,    46,    46,   nil,    46,    46,    46,    46,
    46,   nil,    46,   nil,    46,   nil,   nil,   nil,    46,   nil,
   nil,   nil,   nil,   nil,    46,   nil,    87,    87,    46,    87,
   nil,    87,   nil,   nil,    87,   nil,    46,    46,    87,   nil,
    87,    87,   nil,    87,    87,    87,    87,    87,   nil,    87,
   nil,    87,   nil,   nil,   nil,    87,   nil,   nil,   nil,   nil,
   nil,    87,   nil,    84,    84,    87,    84,   nil,    84,   nil,
    87,    84,   nil,    87,    87,    84,   nil,    84,    84,   nil,
    84,    84,    84,    84,    84,   nil,    84,   nil,    84,   nil,
   nil,   nil,    84,   nil,   nil,   nil,   nil,   nil,    84,   nil,
    73,    73,    84,    73,   nil,    73,   nil,   nil,    73,   nil,
    84,    84,    73,   nil,    73,    73,   nil,    73,    73,    73,
    73,    73,   nil,    73,   nil,    73,   nil,   nil,   nil,    73,
   nil,   nil,   nil,   nil,   nil,    73,    73,    51,    51,    73,
    51,   nil,    51,   nil,   nil,    51,   nil,    73,    73,    51,
   nil,    51,    51,    51,    51,    51,    51,    51,    51,   nil,
    51,   nil,    51,   nil,   nil,   nil,    51,   nil,   nil,   nil,
   nil,   nil,    51,   nil,    70,    70,    51,    70,   nil,    70,
   nil,   nil,    70,   nil,    51,    51,    70,   nil,    70,    70,
   nil,    70,    70,    70,    70,    70,   nil,    70,   nil,    70,
   nil,   nil,    70,    70,   nil,   nil,   nil,   nil,   nil,    70,
   nil,    58,    58,    70,    58,   nil,    58,   nil,   nil,    58,
   nil,    70,    70,    58,   nil,    58,    58,   nil,    58,    58,
    58,    58,    58,   nil,    58,   nil,    58,   nil,   nil,   nil,
    58,   nil,   nil,   nil,   nil,    58,    58,   nil,   nil,   nil,
    58,   nil,   147,   147,   nil,   147,   nil,   147,    58,    58,
   147,   nil,   147,   nil,   147,   nil,   147,   147,   nil,   147,
   147,   147,   147,   147,   nil,   147,   nil,   147,   nil,   nil,
   nil,   147,   nil,   nil,   nil,   nil,   nil,   147,   nil,   nil,
   nil,   147,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   147,
   147 ]

racc_action_pointer = [
   476,   nil,   550,   nil,    49,   nil,   nil,    86,    93,   168,
   nil,    77,   nil,   nil,    81,   279,   nil,   nil,   nil,     3,
   316,   nil,   nil,    93,   nil,   nil,     1,   nil,   nil,     2,
   nil,   nil,   nil,    -2,    83,   nil,    -1,    55,   624,    49,
   698,   739,   nil,   776,     2,    36,   887,   nil,    11,     7,
    41,  1035,    20,    88,    75,    78,    10,   513,  1109,    57,
    55,    50,    21,    26,    60,    77,   nil,   nil,   -12,   -12,
  1072,   nil,   nil,   998,   nil,   nil,     6,    18,   nil,    45,
   nil,   nil,   nil,   nil,   961,    18,   nil,   924,   -13,   850,
    23,   813,   nil,   661,   nil,   -25,   nil,   nil,    76,   587,
    70,    80,   113,   nil,   nil,    55,   nil,   nil,   nil,   nil,
   nil,   439,   nil,   nil,   390,   -18,    50,   353,   -22,    58,
   nil,   nil,   nil,    92,   242,   nil,   100,   112,   104,   nil,
   205,   -37,   nil,    76,   -14,   nil,   nil,   110,   127,   113,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,  1150,   nil,   nil,
   nil ]

racc_action_default = [
   -82,   -55,    -1,   -36,   -18,   -50,    -2,   -82,   -82,   -82,
    -3,   -22,   -17,    -4,   -82,   -82,   -52,   -10,    -5,   -82,
   -82,    -6,   -38,   -82,    -7,   -51,   -42,   -39,    -8,   -72,
   -54,    -9,   -53,   -82,   -82,   -37,   -19,   -82,   -82,   -62,
   -82,   -82,   -56,   -82,   -22,   -62,   -82,   -57,   -78,   -82,
   -82,   -82,   -82,   -25,   -42,   -82,   -45,   -82,   -82,   -72,
   -82,   -72,   -82,   -29,   -82,   -82,   -11,   -75,   -82,   -82,
   -82,   -65,   -58,   -82,   -20,   -23,   -22,   -82,   -59,   -80,
   -77,   -79,   -76,   -12,   -82,   -82,   -40,   -82,   -45,   -82,
   -82,   -82,   -69,   -82,   -73,   -82,   -68,   -71,   -82,   -82,
   -82,   -82,   -31,   151,   -60,   -64,   -66,   -21,   -24,   -61,
   -81,   -27,   -26,   -41,   -82,   -45,   -82,   -82,   -45,   -42,
   -70,   -74,   -67,   -29,   -30,   -14,   -33,   -82,   -82,   -63,
   -82,   -45,   -46,   -42,   -45,   -48,   -43,   -82,   -33,   -82,
   -32,   -15,   -28,   -47,   -44,   -49,   -16,   -33,   -34,   -13,
   -35 ]

racc_goto_table = [
    35,    55,   100,     2,    50,    90,   112,    36,    68,    39,
    38,    34,    41,   128,    77,    45,    52,    43,    46,   139,
    59,    60,    37,    51,    49,   nil,   nil,   nil,   nil,    85,
   nil,   148,   nil,    79,    35,   nil,    35,   116,   nil,    35,
   150,   nil,   nil,    70,    35,   nil,    73,   nil,   nil,    35,
    75,    95,   142,    97,   nil,   nil,   nil,   nil,   nil,   nil,
    91,    93,   137,   nil,   132,   nil,   nil,   135,    35,   nil,
   105,    35,   nil,   nil,   129,   nil,   nil,   nil,   nil,   nil,
   143,   nil,   108,   145,   nil,   nil,   nil,   nil,   nil,    35,
   114,    35,   117,   nil,   136,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   124,   nil,   nil,   nil,   nil,   nil,   144,    35,
   nil,   nil,    35,   nil,   nil,    35,   nil,   nil,   nil,   nil,
   nil,   nil,    35,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   147,   nil,   nil,   nil,    35 ]

racc_goto_check = [
     3,    22,    15,     2,    11,    23,    19,     2,    25,    24,
     2,     1,     2,    16,    25,    24,    13,    18,     2,    14,
    27,    28,    12,     2,    30,   nil,   nil,   nil,   nil,    22,
   nil,    14,   nil,    11,     3,   nil,     3,    23,   nil,     3,
    14,   nil,   nil,     2,     3,   nil,     2,   nil,   nil,     3,
    18,    28,    19,    28,   nil,   nil,   nil,   nil,   nil,   nil,
     2,     2,    15,   nil,    23,   nil,   nil,    23,     3,   nil,
    24,     3,   nil,   nil,    25,   nil,   nil,   nil,   nil,   nil,
    23,   nil,    18,    23,   nil,   nil,   nil,   nil,   nil,     3,
     2,     3,     2,   nil,    22,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,     2,   nil,   nil,   nil,   nil,   nil,    22,     3,
   nil,   nil,     3,   nil,   nil,     3,   nil,   nil,   nil,   nil,
   nil,   nil,     3,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,     2,   nil,   nil,   nil,     3 ]

racc_goto_pointer = [
   nil,    11,     3,    -2,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   -15,    18,    -7,  -107,   -61,   -89,   nil,     6,   -78,
   nil,   nil,   -25,   -51,     1,   -31,   nil,    -9,    -8,   nil,
     5 ]

racc_goto_default = [
   nil,   nil,   111,     3,     6,    10,    13,    18,    21,    24,
    28,    31,   nil,   nil,   nil,   nil,   nil,    12,   nil,   nil,
    22,    27,   nil,   nil,   nil,   nil,    69,   nil,   nil,    61,
   nil ]

racc_token_table = {
 false => 0,
 Object.new => 1,
 :TEXT => 2,
 :BOLD_START => 3,
 :BOLD_END => 4,
 :ITALIC_START => 5,
 :ITALIC_END => 6,
 :LINK_START => 7,
 :LINK_END => 8,
 :LINKSEP => 9,
 :INTLINK_START => 10,
 :INTLINK_END => 11,
 :INTLINKSEP => 12,
 :RESOURCESEP => 13,
 :PRE_START => 14,
 :PRE_END => 15,
 :CHAR_ENT => 16,
 :SECTION_START => 17,
 :SECTION_END => 18,
 :HLINE => 19,
 :SIGNATURE_NAME => 20,
 :SIGNATURE_DATE => 21,
 :SIGNATURE_FULL => 22,
 :PARA_START => 23,
 :PARA_END => 24,
 :UL_START => 25,
 :UL_END => 26,
 :OL_START => 27,
 :OL_END => 28,
 :LI_START => 29,
 :LI_END => 30,
 :DL_START => 31,
 :DL_END => 32,
 :DT_START => 33,
 :DT_END => 34,
 :DD_START => 35,
 :DD_END => 36,
 :TAG_START => 37,
 :TAG_END => 38,
 :ATTR_NAME => 39,
 :ATTR_VALUE => 40,
 :TABLE_START => 41,
 :TABLE_END => 42,
 :ROW_START => 43,
 :ROW_END => 44,
 :HEAD_START => 45,
 :HEAD_END => 46,
 :CELL_START => 47,
 :CELL_END => 48,
 :KEYWORD => 49,
 :VARIABLE_START => 50,
 :VARIABLE_END => 51,
 :CATEGORY => 52 }

racc_use_result_var = true

racc_nt_base = 53

Racc_arg = [
 racc_action_table,
 racc_action_check,
 racc_action_default,
 racc_action_pointer,
 racc_goto_table,
 racc_goto_check,
 racc_goto_default,
 racc_goto_pointer,
 racc_nt_base,
 racc_reduce_table,
 racc_token_table,
 racc_shift_n,
 racc_reduce_n,
 racc_use_result_var ]

Racc_token_to_s_table = [
'$end',
'error',
'TEXT',
'BOLD_START',
'BOLD_END',
'ITALIC_START',
'ITALIC_END',
'LINK_START',
'LINK_END',
'LINKSEP',
'INTLINK_START',
'INTLINK_END',
'INTLINKSEP',
'RESOURCESEP',
'PRE_START',
'PRE_END',
'CHAR_ENT',
'SECTION_START',
'SECTION_END',
'HLINE',
'SIGNATURE_NAME',
'SIGNATURE_DATE',
'SIGNATURE_FULL',
'PARA_START',
'PARA_END',
'UL_START',
'UL_END',
'OL_START',
'OL_END',
'LI_START',
'LI_END',
'DL_START',
'DL_END',
'DT_START',
'DT_END',
'DD_START',
'DD_END',
'TAG_START',
'TAG_END',
'ATTR_NAME',
'ATTR_VALUE',
'TABLE_START',
'TABLE_END',
'ROW_START',
'ROW_END',
'HEAD_START',
'HEAD_END',
'CELL_START',
'CELL_END',
'KEYWORD',
'VARIABLE_START',
'VARIABLE_END',
'CATEGORY',
'$start',
'wiki',
'repeated_contents',
'contents',
'text',
'bulleted_list',
'numbered_list',
'dictionary_list',
'preformatted',
'section',
'tag',
'variable',
'para_contents',
'link_contents',
'reslink_repeated_contents',
'intlink_repeated_contents',
'cat_sort_contents',
'table',
'tag_attributes',
'link_repeated_contents',
'element',
'formatted_element',
'table_contents',
'row_contents',
'list_item',
'list_contents',
'@1',
'dictionary_term',
'dictionary_contents',
'dictionary_definition',
'variable_contents']

Racc_debug_parser = false

##### racc system variables end #####

 # reduce 0 omitted

module_eval <<'.,.,', 'mediawikiparser.y', 29
  def _reduce_1( val, _values, result )
            @nodes.push WikiAST.new
            #@nodes.last.children.insert(0, val[0])
            #puts val[0]
            @nodes.last.children += val[0]
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 36
  def _reduce_2( val, _values, result )
            result = val[0]
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 40
  def _reduce_3( val, _values, result )
            result = val[0]
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 44
  def _reduce_4( val, _values, result )
            result = val[0]
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 51
  def _reduce_5( val, _values, result )
            list = ListAST.new
            list.list_type = :Dictionary
            list.children = val[0]
            result = list
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 55
  def _reduce_6( val, _values, result )
            result = val[0]
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 59
  def _reduce_7( val, _values, result )
            result = val[0]
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 63
  def _reduce_8( val, _values, result )
            result = val[0]
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 67
  def _reduce_9( val, _values, result )
            result = val[0]
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 73
  def _reduce_10( val, _values, result )
            k = KeywordAST.new
            k.text = val[0]
            result = k
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 79
  def _reduce_11( val, _values, result )
            p = ParagraphAST.new
            p.children = val[1]
            result = p
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 86
  def _reduce_12( val, _values, result )
            l = LinkAST.new
            l.url = val[1][0]
            l.children += val[1][1..-1] if val[1].length > 1
            result = l
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 94
  def _reduce_13( val, _values, result )
            l = ResourceLinkAST.new
            l.prefix = val[1]
            l.locator = val[3]
            l.children = val[4] unless val[4].nil? or val[4].empty?
            result = l
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 101
  def _reduce_14( val, _values, result )
            l = InternalLinkAST.new
            l.locator = val[1]
            l.children = val[2] unless val[2].nil? or val[2].empty?
            result = l
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 108
  def _reduce_15( val, _values, result )
            l = CategoryAST.new
            l.locator = val[2]
            l.sort_as = val[3]
            result = l
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 115
  def _reduce_16( val, _values, result )
            l = CategoryLinkAST.new
            l.locator = val[3]
            l.children = val[4] unless val[4].nil? or val[4].empty?
            result = l
   result
  end
.,.,

 # reduce 17 omitted

module_eval <<'.,.,', 'mediawikiparser.y', 122
  def _reduce_18( val, _values, result )
            result = nil
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 126
  def _reduce_19( val, _values, result )
            result = val[0]
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 139
  def _reduce_20( val, _values, result )
            if val[0] != val[2] 
                raise Racc::ParseError.new("XHTML end tag #{val[2]} does not match start tag #{val[0]}")
            end
            elem = ElementAST.new
            elem.name = val[0]
            elem.attributes = val[1]
            result = elem
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 150
  def _reduce_21( val, _values, result )
            if val[0] != val[3] 
                raise Racc::ParseError.new("XHTML end tag #{val[3]} does not match start tag #{val[0]}")
            end
            elem = ElementAST.new
            elem.name = val[0]
            elem.attributes = val[1]
            elem.children += val[2]
            result = elem
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 156
  def _reduce_22( val, _values, result )
            result = nil
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 162
  def _reduce_23( val, _values, result )
            attr_map = val[2] ? val[2] : {}
            attr_map[val[0]] = true
            result = attr_map
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 168
  def _reduce_24( val, _values, result )
            attr_map = val[2] ? val[2] : {}
            attr_map[val[0]] = val[1]
            result = attr_map
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 176
  def _reduce_25( val, _values, result )
            result = val
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 181
  def _reduce_26( val, _values, result )
            result = [val[0]]
            result += val[2]
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 189
  def _reduce_27( val, _values, result )
            result = val[0]
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 194
  def _reduce_28( val, _values, result )
            result = val[0]
            result += val[2] if val[2]
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 201
  def _reduce_29( val, _values, result )
            result = nil
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 205
  def _reduce_30( val, _values, result )
            result = val[1]
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 211
  def _reduce_31( val, _values, result )
            result = nil
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 215
  def _reduce_32( val, _values, result )
            result = val[1]
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 221
  def _reduce_33( val, _values, result )
            result = nil
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 225
  def _reduce_34( val, _values, result )
            result = val[1]
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 232
  def _reduce_35( val, _values, result )
            i = InternalLinkItemAST.new
            i.children = val[1]
            result = [i]
            result += val[2] if val[2]
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 239
  def _reduce_36( val, _values, result )
            result = []
            result << val[0]
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 245
  def _reduce_37( val, _values, result )
            result = []
            result += val[0]
            result << val[1]
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 254
  def _reduce_38( val, _values, result )
            p = TextAST.new
            p.formatting = val[0][0]
            p.contents = val[0][1]
            result = p
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 258
  def _reduce_39( val, _values, result )
            result = val[0]
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 267
  def _reduce_40( val, _values, result )
            table = TableAST.new
            table.children = val[1] unless val[1].nil? or val[1].empty?
            result = table
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 274
  def _reduce_41( val, _values, result )
            table = TableAST.new
            table.options = val[1]
            table.children = val[2] unless val[2].nil? or val[2].empty?
            result = table
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 279
  def _reduce_42( val, _values, result )
            result = nil
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 286
  def _reduce_43( val, _values, result )
            row = TableRowAST.new
            row.children = val[1] unless val[1].nil? or val[1].empty?
            result = [row]
            result += val[3] unless val[3].nil? or val[3].empty?
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 294
  def _reduce_44( val, _values, result )
            row = TableRowAST.new
            row.children = val[2] unless val[2].nil? or val[2].empty?
            row.options = val[1]
            result = [row]
            result += val[4] unless val[4].nil? or val[4].empty?
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 299
  def _reduce_45( val, _values, result )
            result = nil
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 306
  def _reduce_46( val, _values, result )
            cell = TableCellAST.new
            cell.type = :head
            result = [cell]
            result += val[2] unless val[2].nil? or val[2].empty?
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 314
  def _reduce_47( val, _values, result )
            cell = TableCellAST.new
            cell.children = val[1] unless val[1].nil? or val[1].empty?
            cell.type = :head
            result = [cell]
            result += val[3] unless val[3].nil? or val[3].empty?
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 321
  def _reduce_48( val, _values, result )
            cell = TableCellAST.new
            cell.type = :body
            result = [cell]
            result += val[2] unless val[2].nil? or val[2].empty?
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 329
  def _reduce_49( val, _values, result )
            cell = TableCellAST.new
            cell.children = val[1] unless val[1].nil? or val[1].empty?
            cell.type = :body
            result = [cell]
            result += val[3] unless val[3].nil? or val[3].empty?
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 333
  def _reduce_50( val, _values, result )
 return [:None, val[0]]
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 335
  def _reduce_51( val, _values, result )
 return [:HLine, val[0]]
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 337
  def _reduce_52( val, _values, result )
 return [:CharacterEntity, val[0]]
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 339
  def _reduce_53( val, _values, result )
 return [:SignatureDate, val[0]]
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 341
  def _reduce_54( val, _values, result )
 return [:SignatureName, val[0]]
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 343
  def _reduce_55( val, _values, result )
 return [:SignatureFull, val[0]]
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 353
  def _reduce_56( val, _values, result )
            result = FormattedAST.new
            result.formatting = :Bold
            result
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 359
  def _reduce_57( val, _values, result )
            result = FormattedAST.new
            result.formatting = :Italic
            result
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 366
  def _reduce_58( val, _values, result )
            p = FormattedAST.new
            p.formatting = :Bold
            p.children += val[1]
            result = p
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 373
  def _reduce_59( val, _values, result )
            p = FormattedAST.new
            p.formatting = :Italic
            p.children += val[1]
            result = p
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 383
  def _reduce_60( val, _values, result )
            list = ListAST.new
            list.list_type = :Bulleted
            list.children << val[1]
            list.children += val[2]
            result = list
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 393
  def _reduce_61( val, _values, result )
            list = ListAST.new
            list.list_type = :Numbered
            list.children << val[1]
            list.children += val[2]
            result = list
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 396
  def _reduce_62( val, _values, result )
 result = []
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 402
  def _reduce_63( val, _values, result )
            result << val[1]
            result += val[2]
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 403
  def _reduce_64( val, _values, result )
 result = []
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 411
  def _reduce_65( val, _values, result )
            result = ListItemAST.new
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 417
  def _reduce_66( val, _values, result )
            li = ListItemAST.new
            li.children += val[1]
            result = li
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 425
  def _reduce_67( val, _values, result )
            result = [val[1]]
            result += val[2]
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 429
  def _reduce_68( val, _values, result )
            result = val[1]
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 436
  def _reduce_69( val, _values, result )
            result = ListTermAST.new
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 442
  def _reduce_70( val, _values, result )
            term = ListTermAST.new
            term.children += val[1]
            result = term
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 449
  def _reduce_71( val, _values, result )
            result = [val[0]]
            result += val[1] if val[1]
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 453
  def _reduce_72( val, _values, result )
            result = []
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 459
  def _reduce_73( val, _values, result )
            result = ListDefinitionAST.new
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 465
  def _reduce_74( val, _values, result )
            term = ListDefinitionAST.new
            term.children += val[1]
            result = term
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 472
  def _reduce_75( val, _values, result )
            p = PreformattedAST.new
            p.children += val[1]
            result = p
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 480
  def _reduce_76( val, _values, result )
 result = [val[1], val[0].length] 
            s = SectionAST.new
            s.children = val[1]
            s.level = val[0].length
            result = s
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 489
  def _reduce_77( val, _values, result )
            v = VariableAST.new
            v.children = val[1]
            result = v
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 496
  def _reduce_78( val, _values, result )
            result = [val[0]]
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 500
  def _reduce_79( val, _values, result )
            result = [val[0], val[1]]
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 504
  def _reduce_80( val, _values, result )
            result = [val[0], val[1]]
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 508
  def _reduce_81( val, _values, result )
            result = [val[0], val[1], val[2]]
   result
  end
.,.,

 def _reduce_none( val, _values, result )
  result
 end

end   # class MediaWikiParser
