#
# DO NOT MODIFY!!!!
# This file is automatically generated by racc 1.4.5
# from racc grammer file "mediawikiparser.y".
#

require 'racc/parser'


require 'mediacloth/mediawikiast'


class MediaWikiParser < Racc::Parser

module_eval <<'..end mediawikiparser.y modeval..id82fc340af4', 'mediawikiparser.y', 498

attr_accessor :lexer

def initialize
    @nodes = []
    super
end

#Tokenizes input string and parses it.
def parse(input)
    @yydebug=true
    lexer.tokenize(input)
    do_parse
    return @nodes.last
end

#Asks the lexer to return the next token.
def next_token
    return @lexer.lex
end
..end mediawikiparser.y modeval..id82fc340af4

##### racc 1.4.5 generates ###

racc_reduce_table = [
 0, 0, :racc_error,
 1, 54, :_reduce_1,
 1, 56, :_reduce_2,
 1, 56, :_reduce_3,
 1, 56, :_reduce_4,
 1, 56, :_reduce_5,
 1, 56, :_reduce_6,
 1, 56, :_reduce_7,
 1, 56, :_reduce_8,
 1, 56, :_reduce_9,
 1, 56, :_reduce_10,
 3, 56, :_reduce_11,
 3, 56, :_reduce_12,
 6, 56, :_reduce_13,
 4, 56, :_reduce_14,
 5, 56, :_reduce_15,
 6, 56, :_reduce_16,
 1, 56, :_reduce_none,
 0, 65, :_reduce_18,
 1, 65, :_reduce_19,
 3, 63, :_reduce_20,
 4, 63, :_reduce_21,
 0, 71, :_reduce_22,
 2, 71, :_reduce_23,
 3, 71, :_reduce_24,
 1, 66, :_reduce_25,
 3, 66, :_reduce_26,
 1, 72, :_reduce_27,
 3, 72, :_reduce_28,
 0, 68, :_reduce_29,
 2, 68, :_reduce_30,
 0, 69, :_reduce_31,
 2, 69, :_reduce_32,
 0, 67, :_reduce_33,
 2, 67, :_reduce_34,
 3, 67, :_reduce_35,
 1, 55, :_reduce_36,
 2, 55, :_reduce_37,
 1, 57, :_reduce_38,
 1, 57, :_reduce_39,
 3, 70, :_reduce_40,
 4, 70, :_reduce_41,
 0, 75, :_reduce_42,
 4, 75, :_reduce_43,
 5, 75, :_reduce_44,
 0, 76, :_reduce_45,
 3, 76, :_reduce_46,
 4, 76, :_reduce_47,
 3, 76, :_reduce_48,
 4, 76, :_reduce_49,
 1, 73, :_reduce_50,
 1, 73, :_reduce_51,
 1, 73, :_reduce_52,
 1, 73, :_reduce_53,
 1, 73, :_reduce_54,
 1, 73, :_reduce_55,
 2, 74, :_reduce_56,
 2, 74, :_reduce_57,
 3, 74, :_reduce_58,
 3, 74, :_reduce_59,
 4, 58, :_reduce_60,
 4, 59, :_reduce_61,
 0, 79, :_reduce_62,
 3, 78, :_reduce_63,
 0, 78, :_reduce_64,
 2, 77, :_reduce_65,
 3, 77, :_reduce_66,
 4, 60, :_reduce_67,
 3, 60, :_reduce_68,
 2, 80, :_reduce_69,
 3, 80, :_reduce_70,
 2, 81, :_reduce_71,
 0, 81, :_reduce_72,
 2, 82, :_reduce_73,
 3, 82, :_reduce_74,
 3, 61, :_reduce_75,
 3, 62, :_reduce_76,
 3, 64, :_reduce_77 ]

racc_reduce_n = 78

racc_shift_n = 146

racc_action_table = [
    61,     5,     9,    52,    15,    83,    23,    85,   118,    33,
    84,    60,    83,     7,    85,    16,    20,    40,    25,    30,
    32,     1,     4,    83,     8,    85,    14,    83,    80,    85,
    29,    83,    55,    85,    56,    79,    11,    44,    74,    44,
    26,    95,    97,   105,    54,    77,   108,   -64,    17,    19,
    62,     5,     9,    83,    15,    85,    23,    99,    98,    33,
   114,   -64,    64,     7,   117,    16,    20,   100,    25,    30,
    32,     1,     4,    63,     8,   120,    14,   121,    94,   -62,
    29,    56,    51,    92,   128,    48,    11,    56,     5,     9,
    26,    15,    54,    23,    95,    40,    33,   133,    17,    19,
     7,   135,    16,    20,   136,    25,    30,    32,     1,     4,
    44,     8,    54,    14,    54,    82,   141,    29,    40,   144,
   122,   nil,   nil,    11,   nil,   nil,   nil,    26,   nil,     5,
     9,   nil,    15,   nil,    23,    17,    19,    33,   nil,   133,
   nil,     7,   nil,    16,    20,   nil,    25,    30,    32,     1,
     4,   nil,     8,   nil,    14,   nil,   nil,   nil,    29,   nil,
   nil,   nil,   nil,   nil,    11,   nil,   nil,   nil,    26,   nil,
     5,     9,    42,    15,   nil,    23,    17,    19,    33,   nil,
   nil,   nil,     7,   nil,    16,    20,   nil,    25,    30,    32,
     1,     4,   nil,     8,   nil,    14,   nil,   nil,   nil,    29,
   nil,   nil,   nil,   nil,   nil,    11,   nil,     5,     9,    26,
    15,   nil,    23,   nil,   nil,    33,   nil,    17,    19,     7,
   nil,    16,    20,   nil,    25,    30,    32,     1,     4,   nil,
     8,   nil,    14,   nil,   nil,   nil,    29,   nil,   nil,   nil,
   nil,   nil,    11,   nil,     5,     9,    26,    15,   nil,    23,
   nil,   nil,    33,   nil,    17,    19,     7,   nil,    16,    20,
   nil,    25,    30,    32,     1,     4,   nil,     8,   nil,    14,
   nil,   nil,   nil,    29,   nil,   nil,   nil,   nil,   nil,    11,
   nil,     5,     9,    26,    15,    47,    23,   nil,   nil,    33,
   nil,    17,    19,     7,   nil,    16,    20,   nil,    25,    30,
    32,     1,     4,   nil,     8,   nil,    14,   nil,   nil,   nil,
    29,   nil,   nil,   nil,   nil,   nil,    11,   nil,     5,     9,
    26,    15,   nil,    23,   nil,   nil,    33,   nil,    17,    19,
     7,   nil,    16,    20,   nil,    25,    30,    32,     1,     4,
   nil,     8,   nil,    14,   nil,   nil,   nil,    29,   nil,   nil,
   nil,   nil,   nil,    11,   nil,     5,     9,    26,    15,   nil,
    23,   nil,   nil,    33,   129,    17,    19,     7,   nil,    16,
    20,   nil,    25,    30,    32,     1,     4,   nil,     8,   nil,
    14,   nil,   nil,   nil,    29,   nil,   nil,   nil,   nil,   nil,
    11,   nil,     5,     9,    26,    15,   nil,    23,   nil,   nil,
    33,   nil,    17,    19,     7,   nil,    16,    20,   nil,    25,
    30,    32,     1,     4,   nil,     8,   nil,    14,   nil,   nil,
   nil,    29,   nil,   nil,   nil,   nil,   nil,    11,   nil,   nil,
   nil,    26,   nil,   nil,   nil,   nil,   126,   nil,   nil,    17,
    19,     5,     9,   nil,    15,   nil,    23,   nil,   125,    33,
   nil,   nil,   nil,     7,   nil,    16,    20,   nil,    25,    30,
    32,     1,     4,   nil,     8,   nil,    14,   nil,   nil,   nil,
    29,   nil,   nil,   nil,   nil,   nil,    11,   nil,     5,     9,
    26,    15,   nil,    23,   nil,   nil,    33,   nil,    17,    19,
     7,   nil,    16,    20,   nil,    25,    30,    32,     1,     4,
   nil,     8,   nil,    14,   nil,   nil,   nil,    29,   nil,   nil,
    88,   nil,   nil,    11,   nil,     5,     9,    26,    15,   nil,
    23,   nil,   nil,    33,   nil,    17,    19,     7,   nil,    16,
    20,   nil,    25,    30,    32,     1,     4,   nil,     8,   nil,
    14,   nil,   nil,   nil,    29,   nil,   nil,   nil,   nil,   nil,
    11,   nil,     5,     9,    26,    15,   nil,    23,   nil,   nil,
    33,   nil,    17,    19,     7,   nil,    16,    20,   nil,    25,
    30,    32,     1,     4,   nil,     8,   nil,    14,   nil,   nil,
   nil,    29,   nil,   nil,   nil,   nil,   nil,    11,   nil,     5,
     9,    26,    15,   nil,    23,   nil,   nil,    33,   nil,    17,
    19,     7,   nil,    16,    20,   nil,    25,    30,    32,     1,
     4,   nil,     8,   nil,    14,   nil,   nil,   nil,    29,   nil,
   nil,   nil,   nil,   nil,    11,   nil,     5,     9,    26,    15,
   nil,    23,   nil,   nil,    33,   nil,    17,    19,     7,   nil,
    16,    20,   nil,    25,    30,    32,     1,     4,   nil,     8,
   nil,    14,   nil,   nil,   nil,    29,   nil,   nil,   nil,   nil,
   116,    11,   nil,     5,     9,    26,    15,   nil,    23,   nil,
   nil,    33,   nil,    17,    19,     7,    65,    16,    20,   nil,
    25,    30,    32,     1,     4,   nil,     8,   nil,    14,   nil,
   nil,   nil,    29,   nil,   nil,   nil,   nil,   nil,    11,   nil,
     5,     9,    26,    15,   nil,    23,   nil,   nil,    33,   nil,
    17,    19,     7,   nil,    16,    20,   nil,    25,    30,    32,
     1,     4,   nil,     8,   nil,    14,   nil,   nil,   nil,    29,
   nil,   nil,   115,   nil,   nil,    11,   nil,     5,     9,    26,
    15,   nil,    23,   nil,   nil,    33,   nil,    17,    19,     7,
   nil,    16,    20,   nil,    25,    30,    32,     1,     4,   nil,
     8,   nil,    14,   nil,   nil,    69,    29,   nil,   nil,   nil,
   nil,   nil,    11,   nil,   nil,   nil,    26,   nil,     5,     9,
    70,    15,   nil,    23,    17,    19,    33,   nil,   nil,   nil,
     7,   nil,    16,    20,   nil,    25,    30,    32,     1,     4,
   nil,     8,   nil,    14,   nil,   nil,   nil,    29,   nil,   nil,
   nil,   nil,   nil,    11,   nil,     5,     9,    26,    15,   nil,
    23,   nil,   nil,    33,   nil,    17,    19,     7,   nil,    16,
    20,   nil,    25,    30,    32,     1,     4,   nil,     8,   nil,
    14,   nil,   nil,   nil,    29,   nil,   nil,   nil,   nil,   nil,
    11,    72,     5,     9,    26,    15,   nil,    23,   nil,   nil,
    33,   nil,    17,    19,     7,   nil,    16,    20,   nil,    25,
    30,    32,     1,     4,   nil,     8,   nil,    14,   nil,   nil,
   nil,    29,   nil,   nil,   nil,   nil,   nil,    11,   nil,     5,
     9,    26,    15,   nil,    23,   nil,   nil,    33,   113,    17,
    19,     7,   nil,    16,    20,   nil,    25,    30,    32,     1,
     4,   nil,     8,   nil,    14,   nil,   nil,   nil,    29,   nil,
   nil,   nil,   nil,   nil,    11,   nil,     5,     9,    26,    15,
    76,    23,   nil,   110,    33,   nil,    17,    19,     7,   nil,
    16,    20,   nil,    25,    30,    32,     1,     4,   nil,     8,
   nil,    14,   nil,   nil,   nil,    29,   nil,   nil,   nil,   nil,
   nil,    11,   nil,     5,     9,    26,    15,   nil,    23,   nil,
   nil,    33,   nil,    17,    19,     7,   nil,    16,    20,   nil,
    25,    30,    32,     1,     4,   nil,     8,   nil,    14,   nil,
   nil,   nil,    29,   nil,   nil,   nil,   nil,   nil,    11,   nil,
     5,     9,    26,    15,   nil,    23,   nil,   nil,    33,   nil,
    17,    19,     7,   nil,    16,    20,    78,    25,    30,    32,
     1,     4,   nil,     8,   nil,    14,   nil,   nil,   nil,    29,
   nil,   nil,   nil,   nil,   nil,    11,   nil,     5,     9,    26,
    15,   nil,    23,   nil,   nil,    33,   nil,    17,    19,     7,
   nil,    16,    20,   nil,    25,    30,    32,     1,     4,   nil,
     8,   nil,    14,   nil,   nil,   nil,    29,   nil,   nil,   nil,
   nil,   nil,    11,   103,     5,     9,    26,    15,   nil,    23,
   nil,   nil,    33,   nil,    17,    19,     7,   nil,    16,    20,
   nil,    25,    30,    32,     1,     4,   nil,     8,   nil,    14,
   nil,   nil,   102,    29,   nil,   nil,   nil,   nil,   nil,    11,
   nil,     5,     9,    26,    15,   nil,    23,   nil,   nil,    33,
   nil,    17,    19,     7,   nil,    16,    20,   nil,    25,    30,
    32,     1,     4,   nil,     8,   nil,    14,   nil,   nil,   nil,
    29,   nil,   nil,   nil,   nil,    90,    11,   nil,   nil,   nil,
    26,   nil,     5,     9,   nil,    15,   nil,    23,    17,    19,
    33,   nil,   133,   nil,     7,   nil,    16,    20,   nil,    25,
    30,    32,     1,     4,   nil,     8,   nil,    14,   nil,   nil,
   nil,    29,   nil,   nil,   nil,   nil,   nil,    11,   nil,   nil,
   nil,    26,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    17,
    19 ]

racc_action_check = [
    33,    95,    95,    26,    95,   126,    95,   126,    94,    95,
    54,    33,   113,    95,   113,    95,    95,    67,    95,    95,
    95,    95,    95,   110,    95,   110,    95,   129,    51,   129,
    95,    84,    29,    84,    29,    50,    95,    44,    44,    74,
    95,    61,    61,    75,    26,    48,    81,    45,    95,    95,
    33,     4,     4,    54,     4,    54,     4,    63,    62,     4,
    86,    39,    37,     4,    91,     4,     4,    66,     4,     4,
     4,     4,     4,    34,     4,    96,     4,    97,    60,   101,
     4,    59,    23,    58,   111,    19,     4,    57,     7,     7,
     4,     7,   114,     7,   118,    14,     7,   121,     4,     4,
     7,   122,     7,     7,   123,     7,     7,     7,     7,     7,
    11,     7,    52,     7,   128,    53,   132,     7,     8,   134,
    98,   nil,   nil,     7,   nil,   nil,   nil,     7,   nil,   133,
   133,   nil,   133,   nil,   133,     7,     7,   133,   nil,   133,
   nil,   133,   nil,   133,   133,   nil,   133,   133,   133,   133,
   133,   nil,   133,   nil,   133,   nil,   nil,   nil,   133,   nil,
   nil,   nil,   nil,   nil,   133,   nil,   nil,   nil,   133,   nil,
     9,     9,     9,     9,   nil,     9,   133,   133,     9,   nil,
   nil,   nil,     9,   nil,     9,     9,   nil,     9,     9,     9,
     9,     9,   nil,     9,   nil,     9,   nil,   nil,   nil,     9,
   nil,   nil,   nil,   nil,   nil,     9,   nil,   125,   125,     9,
   125,   nil,   125,   nil,   nil,   125,   nil,     9,     9,   125,
   nil,   125,   125,   nil,   125,   125,   125,   125,   125,   nil,
   125,   nil,   125,   nil,   nil,   nil,   125,   nil,   nil,   nil,
   nil,   nil,   125,   nil,   119,   119,   125,   119,   nil,   119,
   nil,   nil,   119,   nil,   125,   125,   119,   nil,   119,   119,
   nil,   119,   119,   119,   119,   119,   nil,   119,   nil,   119,
   nil,   nil,   nil,   119,   nil,   nil,   nil,   nil,   nil,   119,
   nil,    15,    15,   119,    15,    15,    15,   nil,   nil,    15,
   nil,   119,   119,    15,   nil,    15,    15,   nil,    15,    15,
    15,    15,    15,   nil,    15,   nil,    15,   nil,   nil,   nil,
    15,   nil,   nil,   nil,   nil,   nil,    15,   nil,   112,   112,
    15,   112,   nil,   112,   nil,   nil,   112,   nil,    15,    15,
   112,   nil,   112,   112,   nil,   112,   112,   112,   112,   112,
   nil,   112,   nil,   112,   nil,   nil,   nil,   112,   nil,   nil,
   nil,   nil,   nil,   112,   nil,    20,    20,   112,    20,   nil,
    20,   nil,   nil,    20,   112,   112,   112,    20,   nil,    20,
    20,   nil,    20,    20,    20,    20,    20,   nil,    20,   nil,
    20,   nil,   nil,   nil,    20,   nil,   nil,   nil,   nil,   nil,
    20,   nil,   109,   109,    20,   109,   nil,   109,   nil,   nil,
   109,   nil,    20,    20,   109,   nil,   109,   109,   nil,   109,
   109,   109,   109,   109,   nil,   109,   nil,   109,   nil,   nil,
   nil,   109,   nil,   nil,   nil,   nil,   nil,   109,   nil,   nil,
   nil,   109,   nil,   nil,   nil,   nil,   109,   nil,   nil,   109,
   109,   106,   106,   nil,   106,   nil,   106,   nil,   106,   106,
   nil,   nil,   nil,   106,   nil,   106,   106,   nil,   106,   106,
   106,   106,   106,   nil,   106,   nil,   106,   nil,   nil,   nil,
   106,   nil,   nil,   nil,   nil,   nil,   106,   nil,    55,    55,
   106,    55,   nil,    55,   nil,   nil,    55,   nil,   106,   106,
    55,   nil,    55,    55,   nil,    55,    55,    55,    55,    55,
   nil,    55,   nil,    55,   nil,   nil,   nil,    55,   nil,   nil,
    55,   nil,   nil,    55,   nil,     0,     0,    55,     0,   nil,
     0,   nil,   nil,     0,   nil,    55,    55,     0,   nil,     0,
     0,   nil,     0,     0,     0,     0,     0,   nil,     0,   nil,
     0,   nil,   nil,   nil,     0,   nil,   nil,   nil,   nil,   nil,
     0,   nil,     2,     2,     0,     2,   nil,     2,   nil,   nil,
     2,   nil,     0,     0,     2,   nil,     2,     2,   nil,     2,
     2,     2,     2,     2,   nil,     2,   nil,     2,   nil,   nil,
   nil,     2,   nil,   nil,   nil,   nil,   nil,     2,   nil,    36,
    36,     2,    36,   nil,    36,   nil,   nil,    36,   nil,     2,
     2,    36,   nil,    36,    36,   nil,    36,    36,    36,    36,
    36,   nil,    36,   nil,    36,   nil,   nil,   nil,    36,   nil,
   nil,   nil,   nil,   nil,    36,   nil,    89,    89,    36,    89,
   nil,    89,   nil,   nil,    89,   nil,    36,    36,    89,   nil,
    89,    89,   nil,    89,    89,    89,    89,    89,   nil,    89,
   nil,    89,   nil,   nil,   nil,    89,   nil,   nil,   nil,   nil,
    89,    89,   nil,    38,    38,    89,    38,   nil,    38,   nil,
   nil,    38,   nil,    89,    89,    38,    38,    38,    38,   nil,
    38,    38,    38,    38,    38,   nil,    38,   nil,    38,   nil,
   nil,   nil,    38,   nil,   nil,   nil,   nil,   nil,    38,   nil,
    87,    87,    38,    87,   nil,    87,   nil,   nil,    87,   nil,
    38,    38,    87,   nil,    87,    87,   nil,    87,    87,    87,
    87,    87,   nil,    87,   nil,    87,   nil,   nil,   nil,    87,
   nil,   nil,    87,   nil,   nil,    87,   nil,    40,    40,    87,
    40,   nil,    40,   nil,   nil,    40,   nil,    87,    87,    40,
   nil,    40,    40,   nil,    40,    40,    40,    40,    40,   nil,
    40,   nil,    40,   nil,   nil,    40,    40,   nil,   nil,   nil,
   nil,   nil,    40,   nil,   nil,   nil,    40,   nil,    41,    41,
    41,    41,   nil,    41,    40,    40,    41,   nil,   nil,   nil,
    41,   nil,    41,    41,   nil,    41,    41,    41,    41,    41,
   nil,    41,   nil,    41,   nil,   nil,   nil,    41,   nil,   nil,
   nil,   nil,   nil,    41,   nil,    43,    43,    41,    43,   nil,
    43,   nil,   nil,    43,   nil,    41,    41,    43,   nil,    43,
    43,   nil,    43,    43,    43,    43,    43,   nil,    43,   nil,
    43,   nil,   nil,   nil,    43,   nil,   nil,   nil,   nil,   nil,
    43,    43,    85,    85,    43,    85,   nil,    85,   nil,   nil,
    85,   nil,    43,    43,    85,   nil,    85,    85,   nil,    85,
    85,    85,    85,    85,   nil,    85,   nil,    85,   nil,   nil,
   nil,    85,   nil,   nil,   nil,   nil,   nil,    85,   nil,    83,
    83,    85,    83,   nil,    83,   nil,   nil,    83,    85,    85,
    85,    83,   nil,    83,    83,   nil,    83,    83,    83,    83,
    83,   nil,    83,   nil,    83,   nil,   nil,   nil,    83,   nil,
   nil,   nil,   nil,   nil,    83,   nil,    46,    46,    83,    46,
    46,    46,   nil,    83,    46,   nil,    83,    83,    46,   nil,
    46,    46,   nil,    46,    46,    46,    46,    46,   nil,    46,
   nil,    46,   nil,   nil,   nil,    46,   nil,   nil,   nil,   nil,
   nil,    46,   nil,    80,    80,    46,    80,   nil,    80,   nil,
   nil,    80,   nil,    46,    46,    80,   nil,    80,    80,   nil,
    80,    80,    80,    80,    80,   nil,    80,   nil,    80,   nil,
   nil,   nil,    80,   nil,   nil,   nil,   nil,   nil,    80,   nil,
    49,    49,    80,    49,   nil,    49,   nil,   nil,    49,   nil,
    80,    80,    49,   nil,    49,    49,    49,    49,    49,    49,
    49,    49,   nil,    49,   nil,    49,   nil,   nil,   nil,    49,
   nil,   nil,   nil,   nil,   nil,    49,   nil,    71,    71,    49,
    71,   nil,    71,   nil,   nil,    71,   nil,    49,    49,    71,
   nil,    71,    71,   nil,    71,    71,    71,    71,    71,   nil,
    71,   nil,    71,   nil,   nil,   nil,    71,   nil,   nil,   nil,
   nil,   nil,    71,    71,    68,    68,    71,    68,   nil,    68,
   nil,   nil,    68,   nil,    71,    71,    68,   nil,    68,    68,
   nil,    68,    68,    68,    68,    68,   nil,    68,   nil,    68,
   nil,   nil,    68,    68,   nil,   nil,   nil,   nil,   nil,    68,
   nil,    56,    56,    68,    56,   nil,    56,   nil,   nil,    56,
   nil,    68,    68,    56,   nil,    56,    56,   nil,    56,    56,
    56,    56,    56,   nil,    56,   nil,    56,   nil,   nil,   nil,
    56,   nil,   nil,   nil,   nil,    56,    56,   nil,   nil,   nil,
    56,   nil,   142,   142,   nil,   142,   nil,   142,    56,    56,
   142,   nil,   142,   nil,   142,   nil,   142,   142,   nil,   142,
   142,   142,   142,   142,   nil,   142,   nil,   142,   nil,   nil,
   nil,   142,   nil,   nil,   nil,   nil,   nil,   142,   nil,   nil,
   nil,   142,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   142,
   142 ]

racc_action_pointer = [
   513,   nil,   550,   nil,    49,   nil,   nil,    86,    89,   168,
   nil,    71,   nil,   nil,    66,   279,   nil,   nil,   nil,    83,
   353,   nil,   nil,    80,   nil,   nil,     1,   nil,   nil,    -1,
   nil,   nil,   nil,    -2,    73,   nil,   587,    38,   661,    35,
   735,   776,   nil,   813,    -2,    19,   924,   nil,    -6,   998,
    27,    19,    69,    73,     8,   476,  1109,    52,    51,    46,
    26,    29,    56,    57,   nil,   nil,    41,   -12,  1072,   nil,
   nil,  1035,   nil,   nil,     0,    15,   nil,   nil,   nil,   nil,
   961,     4,   nil,   887,   -14,   850,    16,   698,   nil,   624,
   nil,    32,   nil,   nil,     6,    -1,    64,    75,   108,   nil,
   nil,    50,   nil,   nil,   nil,   nil,   439,   nil,   nil,   390,
   -22,    40,   316,   -33,    49,   nil,   nil,   nil,    82,   242,
   nil,    85,    99,    93,   nil,   205,   -40,   nil,    71,   -18,
   nil,   nil,   105,   127,   108,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,  1150,   nil,   nil,   nil ]

racc_action_default = [
   -78,   -55,    -1,   -36,   -18,   -50,    -2,   -78,   -78,   -78,
    -3,   -22,   -17,    -4,   -78,   -78,   -52,   -10,    -5,   -78,
   -78,    -6,   -38,   -78,    -7,   -51,   -42,   -39,    -8,   -72,
   -54,    -9,   -53,   -78,   -78,   -37,   -19,   -78,   -78,   -62,
   -78,   -78,   -56,   -78,   -22,   -62,   -78,   -57,   -78,   -78,
   -78,   -25,   -42,   -78,   -45,   -78,   -78,   -72,   -78,   -72,
   -78,   -29,   -78,   -78,   -11,   -75,   -78,   -78,   -78,   -65,
   -58,   -78,   -20,   -23,   -22,   -78,   -59,   -77,   -76,   -12,
   -78,   -78,   -40,   -78,   -45,   -78,   -78,   -78,   -69,   -78,
   -73,   -78,   -68,   -71,   -78,   -78,   -78,   -78,   -31,   146,
   -60,   -64,   -66,   -21,   -24,   -61,   -27,   -26,   -41,   -78,
   -45,   -78,   -78,   -45,   -42,   -70,   -74,   -67,   -29,   -30,
   -14,   -33,   -78,   -78,   -63,   -78,   -45,   -46,   -42,   -45,
   -48,   -43,   -78,   -33,   -78,   -32,   -15,   -28,   -47,   -44,
   -49,   -16,   -33,   -34,   -13,   -35 ]

racc_goto_table = [
    35,    53,    58,     2,    43,    86,    96,    36,    66,    39,
    38,   107,    41,    37,    75,    45,    50,   134,    46,   123,
    57,    34,   nil,    49,   nil,   nil,   nil,    81,   nil,   143,
    91,   nil,    93,   nil,    35,   111,    35,    73,   145,    35,
   nil,   nil,   nil,    68,    35,   nil,    71,    35,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   137,   nil,    87,    89,
   nil,   127,   nil,   132,   130,   nil,    35,   104,   101,    35,
   124,   nil,   nil,   nil,   nil,   nil,   nil,   138,   nil,   nil,
   140,   nil,   nil,   nil,   nil,    35,   109,    35,   112,   131,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   119,   nil,
   nil,   nil,   nil,   139,    35,   nil,   nil,    35,   nil,   nil,
    35,   nil,   nil,   nil,   nil,   nil,   nil,    35,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   142,   nil,   nil,   nil,
    35 ]

racc_goto_check = [
     3,    22,    28,     2,    18,    23,    15,     2,    25,    24,
     2,    19,     2,    12,    25,    24,    13,    14,     2,    16,
    27,     1,   nil,     2,   nil,   nil,   nil,    22,   nil,    14,
    28,   nil,    28,   nil,     3,    23,     3,    18,    14,     3,
   nil,   nil,   nil,     2,     3,   nil,     2,     3,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,    19,   nil,     2,     2,
   nil,    23,   nil,    15,    23,   nil,     3,    18,    24,     3,
    25,   nil,   nil,   nil,   nil,   nil,   nil,    23,   nil,   nil,
    23,   nil,   nil,   nil,   nil,     3,     2,     3,     2,    22,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,     2,   nil,
   nil,   nil,   nil,    22,     3,   nil,   nil,     3,   nil,   nil,
     3,   nil,   nil,   nil,   nil,   nil,   nil,     3,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,     2,   nil,   nil,   nil,
     3 ]

racc_goto_pointer = [
   nil,    21,     3,    -2,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,     9,    -7,  -104,   -55,   -79,   nil,    -7,   -69,
   nil,   nil,   -25,   -49,     1,   -31,   nil,    -9,   -27,   nil ]

racc_goto_default = [
   nil,   nil,   106,     3,     6,    10,    13,    18,    21,    24,
    28,    31,   nil,   nil,   nil,   nil,   nil,    12,   nil,   nil,
    22,    27,   nil,   nil,   nil,   nil,    67,   nil,   nil,    59 ]

racc_token_table = {
 false => 0,
 Object.new => 1,
 :TEXT => 2,
 :BOLD_START => 3,
 :BOLD_END => 4,
 :ITALIC_START => 5,
 :ITALIC_END => 6,
 :LINK_START => 7,
 :LINK_END => 8,
 :LINKSEP => 9,
 :INTLINK_START => 10,
 :INTLINK_END => 11,
 :INTLINKSEP => 12,
 :RESOURCESEP => 13,
 :PRE_START => 14,
 :PRE_END => 15,
 :CHAR_ENT => 16,
 :SECTION_START => 17,
 :SECTION_END => 18,
 :HLINE => 19,
 :SIGNATURE_NAME => 20,
 :SIGNATURE_DATE => 21,
 :SIGNATURE_FULL => 22,
 :PARA_START => 23,
 :PARA_END => 24,
 :UL_START => 25,
 :UL_END => 26,
 :OL_START => 27,
 :OL_END => 28,
 :LI_START => 29,
 :LI_END => 30,
 :DL_START => 31,
 :DL_END => 32,
 :DT_START => 33,
 :DT_END => 34,
 :DD_START => 35,
 :DD_END => 36,
 :TAG_START => 37,
 :TAG_END => 38,
 :ATTR_NAME => 39,
 :ATTR_VALUE => 40,
 :TABLE_START => 41,
 :TABLE_END => 42,
 :ROW_START => 43,
 :ROW_END => 44,
 :HEAD_START => 45,
 :HEAD_END => 46,
 :CELL_START => 47,
 :CELL_END => 48,
 :KEYWORD => 49,
 :VARIABLE_START => 50,
 :VARIABLE_END => 51,
 :CATEGORY => 52 }

racc_use_result_var = true

racc_nt_base = 53

Racc_arg = [
 racc_action_table,
 racc_action_check,
 racc_action_default,
 racc_action_pointer,
 racc_goto_table,
 racc_goto_check,
 racc_goto_default,
 racc_goto_pointer,
 racc_nt_base,
 racc_reduce_table,
 racc_token_table,
 racc_shift_n,
 racc_reduce_n,
 racc_use_result_var ]

Racc_token_to_s_table = [
'$end',
'error',
'TEXT',
'BOLD_START',
'BOLD_END',
'ITALIC_START',
'ITALIC_END',
'LINK_START',
'LINK_END',
'LINKSEP',
'INTLINK_START',
'INTLINK_END',
'INTLINKSEP',
'RESOURCESEP',
'PRE_START',
'PRE_END',
'CHAR_ENT',
'SECTION_START',
'SECTION_END',
'HLINE',
'SIGNATURE_NAME',
'SIGNATURE_DATE',
'SIGNATURE_FULL',
'PARA_START',
'PARA_END',
'UL_START',
'UL_END',
'OL_START',
'OL_END',
'LI_START',
'LI_END',
'DL_START',
'DL_END',
'DT_START',
'DT_END',
'DD_START',
'DD_END',
'TAG_START',
'TAG_END',
'ATTR_NAME',
'ATTR_VALUE',
'TABLE_START',
'TABLE_END',
'ROW_START',
'ROW_END',
'HEAD_START',
'HEAD_END',
'CELL_START',
'CELL_END',
'KEYWORD',
'VARIABLE_START',
'VARIABLE_END',
'CATEGORY',
'$start',
'wiki',
'repeated_contents',
'contents',
'text',
'bulleted_list',
'numbered_list',
'dictionary_list',
'preformatted',
'section',
'tag',
'variable',
'para_contents',
'link_contents',
'reslink_repeated_contents',
'intlink_repeated_contents',
'cat_sort_contents',
'table',
'tag_attributes',
'link_repeated_contents',
'element',
'formatted_element',
'table_contents',
'row_contents',
'list_item',
'list_contents',
'@1',
'dictionary_term',
'dictionary_contents',
'dictionary_definition']

Racc_debug_parser = false

##### racc system variables end #####

 # reduce 0 omitted

module_eval <<'.,.,', 'mediawikiparser.y', 29
  def _reduce_1( val, _values, result )
            @nodes.push WikiAST.new
            #@nodes.last.children.insert(0, val[0])
            #puts val[0]
            @nodes.last.children += val[0]
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 36
  def _reduce_2( val, _values, result )
            result = val[0]
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 40
  def _reduce_3( val, _values, result )
            result = val[0]
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 44
  def _reduce_4( val, _values, result )
            result = val[0]
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 51
  def _reduce_5( val, _values, result )
            list = ListAST.new
            list.list_type = :Dictionary
            list.children = val[0]
            result = list
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 55
  def _reduce_6( val, _values, result )
            result = val[0]
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 59
  def _reduce_7( val, _values, result )
            result = val[0]
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 63
  def _reduce_8( val, _values, result )
            result = val[0]
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 67
  def _reduce_9( val, _values, result )
            result = val[0]
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 73
  def _reduce_10( val, _values, result )
            k = KeywordAST.new
            k.text = val[0]
            result = k
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 79
  def _reduce_11( val, _values, result )
            p = ParagraphAST.new
            p.children = val[1]
            result = p
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 86
  def _reduce_12( val, _values, result )
            l = LinkAST.new
            l.url = val[1][0]
            l.children += val[1][1..-1] if val[1].length > 1
            result = l
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 94
  def _reduce_13( val, _values, result )
            l = ResourceLinkAST.new
            l.prefix = val[1]
            l.locator = val[3]
            l.children = val[4] unless val[4].nil? or val[4].empty?
            result = l
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 101
  def _reduce_14( val, _values, result )
            l = InternalLinkAST.new
            l.locator = val[1]
            l.children = val[2] unless val[2].nil? or val[2].empty?
            result = l
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 108
  def _reduce_15( val, _values, result )
            l = CategoryAST.new
            l.locator = val[2]
            l.sort_as = val[3]
            result = l
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 115
  def _reduce_16( val, _values, result )
            l = CategoryLinkAST.new
            l.locator = val[3]
            l.children = val[4] unless val[4].nil? or val[4].empty?
            result = l
   result
  end
.,.,

 # reduce 17 omitted

module_eval <<'.,.,', 'mediawikiparser.y', 122
  def _reduce_18( val, _values, result )
            result = nil
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 126
  def _reduce_19( val, _values, result )
            result = val[0]
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 139
  def _reduce_20( val, _values, result )
            if val[0] != val[2] 
                raise Racc::ParseError.new("XHTML end tag #{val[2]} does not match start tag #{val[0]}")
            end
            elem = ElementAST.new
            elem.name = val[0]
            elem.attributes = val[1]
            result = elem
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 150
  def _reduce_21( val, _values, result )
            if val[0] != val[3] 
                raise Racc::ParseError.new("XHTML end tag #{val[3]} does not match start tag #{val[0]}")
            end
            elem = ElementAST.new
            elem.name = val[0]
            elem.attributes = val[1]
            elem.children += val[2]
            result = elem
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 156
  def _reduce_22( val, _values, result )
            result = nil
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 162
  def _reduce_23( val, _values, result )
            attr_map = val[2] ? val[2] : {}
            attr_map[val[0]] = true
            result = attr_map
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 168
  def _reduce_24( val, _values, result )
            attr_map = val[2] ? val[2] : {}
            attr_map[val[0]] = val[1]
            result = attr_map
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 176
  def _reduce_25( val, _values, result )
            result = val
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 181
  def _reduce_26( val, _values, result )
            result = [val[0]]
            result += val[2]
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 189
  def _reduce_27( val, _values, result )
            result = val[0]
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 194
  def _reduce_28( val, _values, result )
            result = val[0]
            result += val[2] if val[2]
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 201
  def _reduce_29( val, _values, result )
            result = nil
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 205
  def _reduce_30( val, _values, result )
            result = val[1]
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 211
  def _reduce_31( val, _values, result )
            result = nil
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 215
  def _reduce_32( val, _values, result )
            result = val[1]
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 221
  def _reduce_33( val, _values, result )
            result = nil
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 225
  def _reduce_34( val, _values, result )
            result = val[1]
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 232
  def _reduce_35( val, _values, result )
            i = InternalLinkItemAST.new
            i.children = val[1]
            result = [i]
            result += val[2] if val[2]
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 239
  def _reduce_36( val, _values, result )
            result = []
            result << val[0]
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 245
  def _reduce_37( val, _values, result )
            result = []
            result += val[0]
            result << val[1]
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 254
  def _reduce_38( val, _values, result )
            p = TextAST.new
            p.formatting = val[0][0]
            p.contents = val[0][1]
            result = p
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 258
  def _reduce_39( val, _values, result )
            result = val[0]
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 267
  def _reduce_40( val, _values, result )
            table = TableAST.new
            table.children = val[1] unless val[1].nil? or val[1].empty?
            result = table
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 274
  def _reduce_41( val, _values, result )
            table = TableAST.new
            table.options = val[1]
            table.children = val[2] unless val[2].nil? or val[2].empty?
            result = table
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 279
  def _reduce_42( val, _values, result )
            result = nil
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 286
  def _reduce_43( val, _values, result )
            row = TableRowAST.new
            row.children = val[1] unless val[1].nil? or val[1].empty?
            result = [row]
            result += val[3] unless val[3].nil? or val[3].empty?
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 294
  def _reduce_44( val, _values, result )
            row = TableRowAST.new
            row.children = val[2] unless val[2].nil? or val[2].empty?
            row.options = val[1]
            result = [row]
            result += val[4] unless val[4].nil? or val[4].empty?
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 299
  def _reduce_45( val, _values, result )
            result = nil
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 306
  def _reduce_46( val, _values, result )
            cell = TableCellAST.new
            cell.type = :head
            result = [cell]
            result += val[2] unless val[2].nil? or val[2].empty?
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 314
  def _reduce_47( val, _values, result )
            cell = TableCellAST.new
            cell.children = val[1] unless val[1].nil? or val[1].empty?
            cell.type = :head
            result = [cell]
            result += val[3] unless val[3].nil? or val[3].empty?
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 321
  def _reduce_48( val, _values, result )
            cell = TableCellAST.new
            cell.type = :body
            result = [cell]
            result += val[2] unless val[2].nil? or val[2].empty?
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 329
  def _reduce_49( val, _values, result )
            cell = TableCellAST.new
            cell.children = val[1] unless val[1].nil? or val[1].empty?
            cell.type = :body
            result = [cell]
            result += val[3] unless val[3].nil? or val[3].empty?
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 333
  def _reduce_50( val, _values, result )
 return [:None, val[0]]
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 335
  def _reduce_51( val, _values, result )
 return [:HLine, val[0]]
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 337
  def _reduce_52( val, _values, result )
 return [:CharacterEntity, val[0]]
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 339
  def _reduce_53( val, _values, result )
 return [:SignatureDate, val[0]]
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 341
  def _reduce_54( val, _values, result )
 return [:SignatureName, val[0]]
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 343
  def _reduce_55( val, _values, result )
 return [:SignatureFull, val[0]]
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 353
  def _reduce_56( val, _values, result )
            result = FormattedAST.new
            result.formatting = :Bold
            result
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 359
  def _reduce_57( val, _values, result )
            result = FormattedAST.new
            result.formatting = :Italic
            result
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 366
  def _reduce_58( val, _values, result )
            p = FormattedAST.new
            p.formatting = :Bold
            p.children += val[1]
            result = p
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 373
  def _reduce_59( val, _values, result )
            p = FormattedAST.new
            p.formatting = :Italic
            p.children += val[1]
            result = p
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 383
  def _reduce_60( val, _values, result )
            list = ListAST.new
            list.list_type = :Bulleted
            list.children << val[1]
            list.children += val[2]
            result = list
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 393
  def _reduce_61( val, _values, result )
            list = ListAST.new
            list.list_type = :Numbered
            list.children << val[1]
            list.children += val[2]
            result = list
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 396
  def _reduce_62( val, _values, result )
 result = []
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 402
  def _reduce_63( val, _values, result )
            result << val[1]
            result += val[2]
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 403
  def _reduce_64( val, _values, result )
 result = []
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 411
  def _reduce_65( val, _values, result )
            result = ListItemAST.new
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 417
  def _reduce_66( val, _values, result )
            li = ListItemAST.new
            li.children += val[1]
            result = li
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 425
  def _reduce_67( val, _values, result )
            result = [val[1]]
            result += val[2]
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 429
  def _reduce_68( val, _values, result )
            result = val[1]
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 436
  def _reduce_69( val, _values, result )
            result = ListTermAST.new
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 442
  def _reduce_70( val, _values, result )
            term = ListTermAST.new
            term.children += val[1]
            result = term
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 449
  def _reduce_71( val, _values, result )
            result = [val[0]]
            result += val[1] if val[1]
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 453
  def _reduce_72( val, _values, result )
            result = []
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 459
  def _reduce_73( val, _values, result )
            result = ListDefinitionAST.new
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 465
  def _reduce_74( val, _values, result )
            term = ListDefinitionAST.new
            term.children += val[1]
            result = term
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 472
  def _reduce_75( val, _values, result )
            p = PreformattedAST.new
            p.children += val[1]
            result = p
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 480
  def _reduce_76( val, _values, result )
 result = [val[1], val[0].length] 
            s = SectionAST.new
            s.children = val[1]
            s.level = val[0].length
            result = s
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 489
  def _reduce_77( val, _values, result )
            v = VariableAST.new
            v.text = val[1]
            result = v
   result
  end
.,.,

 def _reduce_none( val, _values, result )
  result
 end

end   # class MediaWikiParser
