#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.4.5
# from Racc grammer file "".
#

require 'racc/parser.rb'

require 'mediacloth/mediawikiast'

class MediaWikiParser < Racc::Parser

module_eval(<<'...end mediawikiparser.y/module_eval...', 'mediawikiparser.y', 512)

attr_accessor :lexer

def initialize
    @nodes = []
    super
end

#Tokenizes input string and parses it.
def parse(input)
    @yydebug=true
    lexer.tokenize(input)
    do_parse
    return @nodes.last
end

#Asks the lexer to return the next token.
def next_token
    return @lexer.lex
end
...end mediawikiparser.y/module_eval...
##### State transition tables begin ###

racc_action_table = [
    61,     5,     9,    52,    15,    84,    23,    86,   121,    33,
    85,    60,    84,     7,    86,    16,    20,    40,    25,    30,
    32,     1,     4,    84,     8,    86,    14,    84,    81,    86,
    29,    84,    55,    86,    56,    80,    11,    44,    74,    44,
    26,    96,    98,   106,    54,   107,   108,    77,    17,    19,
    62,     5,     9,    84,    15,    86,    23,   111,   -64,    33,
   100,    99,   117,     7,   -64,    16,    20,    64,    25,    30,
    32,     1,     4,   120,     8,   101,    14,    63,   123,   124,
    29,   125,    95,    77,    56,    51,    11,    93,     5,     9,
    26,    15,   132,    23,    48,    56,    33,    54,    17,    19,
     7,    96,    16,    20,    40,    25,    30,    32,     1,     4,
   137,     8,   139,    14,   140,    44,    54,    29,    54,    83,
   145,    40,   148,    11,   -62,   nil,   nil,    26,   nil,     5,
     9,   nil,    15,   nil,    23,    17,    19,    33,   nil,   137,
   nil,     7,   nil,    16,    20,   nil,    25,    30,    32,     1,
     4,   nil,     8,   nil,    14,   nil,   nil,   nil,    29,   nil,
   nil,   nil,   nil,   nil,    11,   nil,   nil,   nil,    26,   nil,
     5,     9,    42,    15,   nil,    23,    17,    19,    33,   nil,
   nil,   nil,     7,   nil,    16,    20,   nil,    25,    30,    32,
     1,     4,   nil,     8,   nil,    14,   nil,   nil,   nil,    29,
   nil,   nil,   nil,   nil,   nil,    11,   nil,     5,     9,    26,
    15,   nil,    23,   nil,   nil,    33,   nil,    17,    19,     7,
   nil,    16,    20,   nil,    25,    30,    32,     1,     4,   nil,
     8,   nil,    14,   nil,   nil,   nil,    29,   nil,   nil,   nil,
   nil,   nil,    11,   nil,     5,     9,    26,    15,   nil,    23,
   nil,   nil,    33,   nil,    17,    19,     7,   nil,    16,    20,
   nil,    25,    30,    32,     1,     4,   nil,     8,   nil,    14,
   nil,   nil,   nil,    29,   nil,   nil,   nil,   nil,   nil,    11,
   nil,     5,     9,    26,    15,    47,    23,   nil,   nil,    33,
   nil,    17,    19,     7,   nil,    16,    20,   nil,    25,    30,
    32,     1,     4,   nil,     8,   nil,    14,   nil,   nil,   nil,
    29,   nil,   nil,   nil,   nil,   nil,    11,   nil,     5,     9,
    26,    15,   nil,    23,   nil,   nil,    33,   nil,    17,    19,
     7,   nil,    16,    20,   nil,    25,    30,    32,     1,     4,
   nil,     8,   nil,    14,   nil,   nil,   nil,    29,   nil,   nil,
   nil,   nil,   nil,    11,   nil,     5,     9,    26,    15,   nil,
    23,   nil,   nil,    33,   133,    17,    19,     7,   nil,    16,
    20,   nil,    25,    30,    32,     1,     4,   nil,     8,   nil,
    14,   nil,   nil,   nil,    29,   nil,   nil,   nil,   nil,   nil,
    11,   nil,     5,     9,    26,    15,   nil,    23,   nil,   nil,
    33,   nil,    17,    19,     7,   nil,    16,    20,   nil,    25,
    30,    32,     1,     4,   nil,     8,   nil,    14,   nil,   nil,
   nil,    29,   nil,   nil,   nil,   nil,   nil,    11,   nil,   nil,
   nil,    26,   nil,   nil,   nil,   nil,   130,   nil,   nil,    17,
    19,     5,     9,   nil,    15,   nil,    23,   nil,   129,    33,
   nil,   nil,   nil,     7,   nil,    16,    20,   nil,    25,    30,
    32,     1,     4,   nil,     8,   nil,    14,   nil,   nil,   nil,
    29,   nil,   nil,   nil,   nil,   nil,    11,   nil,     5,     9,
    26,    15,   nil,    23,   nil,   nil,    33,   nil,    17,    19,
     7,   nil,    16,    20,   nil,    25,    30,    32,     1,     4,
   nil,     8,   nil,    14,   nil,   nil,   nil,    29,   nil,   nil,
    89,   nil,   nil,    11,   nil,     5,     9,    26,    15,   nil,
    23,   nil,   nil,    33,   nil,    17,    19,     7,   nil,    16,
    20,   nil,    25,    30,    32,     1,     4,   nil,     8,   nil,
    14,   nil,   nil,   nil,    29,   nil,   nil,   nil,   nil,   nil,
    11,   nil,     5,     9,    26,    15,   nil,    23,   nil,   nil,
    33,   nil,    17,    19,     7,   nil,    16,    20,   nil,    25,
    30,    32,     1,     4,   nil,     8,   nil,    14,   nil,   nil,
   nil,    29,   nil,   nil,   nil,   nil,   nil,    11,   nil,     5,
     9,    26,    15,   nil,    23,   nil,   nil,    33,   nil,    17,
    19,     7,   nil,    16,    20,   nil,    25,    30,    32,     1,
     4,   nil,     8,   nil,    14,   nil,   nil,   nil,    29,   nil,
   nil,   nil,   nil,   nil,    11,   nil,     5,     9,    26,    15,
   nil,    23,   nil,   nil,    33,   nil,    17,    19,     7,   nil,
    16,    20,   nil,    25,    30,    32,     1,     4,   nil,     8,
   nil,    14,   nil,   nil,   nil,    29,   nil,   nil,   nil,   nil,
   119,    11,   nil,     5,     9,    26,    15,   nil,    23,   nil,
   nil,    33,   nil,    17,    19,     7,    65,    16,    20,   nil,
    25,    30,    32,     1,     4,   nil,     8,   nil,    14,   nil,
   nil,   nil,    29,   nil,   nil,   nil,   nil,   nil,    11,   nil,
     5,     9,    26,    15,   nil,    23,   nil,   nil,    33,   nil,
    17,    19,     7,   nil,    16,    20,   nil,    25,    30,    32,
     1,     4,   nil,     8,   nil,    14,   nil,   nil,   nil,    29,
   nil,   nil,   118,   nil,   nil,    11,   nil,     5,     9,    26,
    15,   nil,    23,   nil,   nil,    33,   nil,    17,    19,     7,
   nil,    16,    20,   nil,    25,    30,    32,     1,     4,   nil,
     8,   nil,    14,   nil,   nil,    69,    29,   nil,   nil,   nil,
   nil,   nil,    11,   nil,   nil,   nil,    26,   nil,     5,     9,
    70,    15,   nil,    23,    17,    19,    33,   nil,   nil,   nil,
     7,   nil,    16,    20,   nil,    25,    30,    32,     1,     4,
   nil,     8,   nil,    14,   nil,   nil,   nil,    29,   nil,   nil,
   nil,   nil,   nil,    11,   nil,     5,     9,    26,    15,   nil,
    23,   nil,   nil,    33,   nil,    17,    19,     7,   nil,    16,
    20,   nil,    25,    30,    32,     1,     4,   nil,     8,   nil,
    14,   nil,   nil,   nil,    29,   nil,   nil,   nil,   nil,   nil,
    11,    72,     5,     9,    26,    15,   nil,    23,   nil,   nil,
    33,   nil,    17,    19,     7,   nil,    16,    20,   nil,    25,
    30,    32,     1,     4,   nil,     8,   nil,    14,   nil,   nil,
   nil,    29,   nil,   nil,   nil,   nil,   nil,    11,   nil,     5,
     9,    26,    15,   nil,    23,   nil,   nil,    33,   116,    17,
    19,     7,   nil,    16,    20,   nil,    25,    30,    32,     1,
     4,   nil,     8,   nil,    14,   nil,   nil,   nil,    29,   nil,
   nil,   nil,   nil,   nil,    11,   nil,     5,     9,    26,    15,
    76,    23,   nil,   113,    33,   nil,    17,    19,     7,   nil,
    16,    20,   nil,    25,    30,    32,     1,     4,   nil,     8,
   nil,    14,   nil,   nil,   nil,    29,   nil,   nil,   nil,   nil,
   nil,    11,   nil,     5,     9,    26,    15,   nil,    23,   nil,
   nil,    33,   nil,    17,    19,     7,   nil,    16,    20,   nil,
    25,    30,    32,     1,     4,   nil,     8,   nil,    14,   nil,
   nil,   nil,    29,   nil,   nil,   nil,   nil,   nil,    11,   nil,
     5,     9,    26,    15,   nil,    23,   nil,   nil,    33,   nil,
    17,    19,     7,   nil,    16,    20,    79,    25,    30,    32,
     1,     4,   nil,     8,   nil,    14,   nil,   nil,   nil,    29,
   nil,   nil,   nil,   nil,   nil,    11,   nil,     5,     9,    26,
    15,   nil,    23,   nil,   nil,    33,   nil,    17,    19,     7,
   nil,    16,    20,   nil,    25,    30,    32,     1,     4,   nil,
     8,   nil,    14,   nil,   nil,   nil,    29,   nil,   nil,   nil,
   nil,   nil,    11,   104,     5,     9,    26,    15,   nil,    23,
   nil,   nil,    33,   nil,    17,    19,     7,   nil,    16,    20,
   nil,    25,    30,    32,     1,     4,   nil,     8,   nil,    14,
   nil,   nil,   103,    29,   nil,   nil,   nil,   nil,   nil,    11,
   nil,     5,     9,    26,    15,   nil,    23,   nil,   nil,    33,
   nil,    17,    19,     7,   nil,    16,    20,   nil,    25,    30,
    32,     1,     4,   nil,     8,   nil,    14,   nil,   nil,   nil,
    29,   nil,   nil,   nil,   nil,    91,    11,   nil,   nil,   nil,
    26,   nil,     5,     9,   nil,    15,   nil,    23,    17,    19,
    33,   nil,   137,   nil,     7,   nil,    16,    20,   nil,    25,
    30,    32,     1,     4,   nil,     8,   nil,    14,   nil,   nil,
   nil,    29,   nil,   nil,   nil,   nil,   nil,    11,   nil,   nil,
   nil,    26,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    17,
    19 ]

racc_action_check = [
    33,    96,    96,    26,    96,   130,    96,   130,    95,    96,
    54,    33,   116,    96,   116,    96,    96,    67,    96,    96,
    96,    96,    96,   113,    96,   113,    96,   133,    51,   133,
    96,    85,    29,    85,    29,    50,    96,    44,    44,    74,
    96,    61,    61,    75,    26,    77,    78,    48,    96,    96,
    33,     4,     4,    54,     4,    54,     4,    82,    45,     4,
    63,    62,    87,     4,    39,     4,     4,    37,     4,     4,
     4,     4,     4,    92,     4,    66,     4,    34,    97,    98,
     4,    99,    60,   107,    59,    23,     4,    58,     7,     7,
     4,     7,   114,     7,    19,    57,     7,   117,     4,     4,
     7,   121,     7,     7,    14,     7,     7,     7,     7,     7,
   124,     7,   125,     7,   126,    11,    52,     7,   132,    53,
   136,     8,   138,     7,   102,   nil,   nil,     7,   nil,   137,
   137,   nil,   137,   nil,   137,     7,     7,   137,   nil,   137,
   nil,   137,   nil,   137,   137,   nil,   137,   137,   137,   137,
   137,   nil,   137,   nil,   137,   nil,   nil,   nil,   137,   nil,
   nil,   nil,   nil,   nil,   137,   nil,   nil,   nil,   137,   nil,
     9,     9,     9,     9,   nil,     9,   137,   137,     9,   nil,
   nil,   nil,     9,   nil,     9,     9,   nil,     9,     9,     9,
     9,     9,   nil,     9,   nil,     9,   nil,   nil,   nil,     9,
   nil,   nil,   nil,   nil,   nil,     9,   nil,   129,   129,     9,
   129,   nil,   129,   nil,   nil,   129,   nil,     9,     9,   129,
   nil,   129,   129,   nil,   129,   129,   129,   129,   129,   nil,
   129,   nil,   129,   nil,   nil,   nil,   129,   nil,   nil,   nil,
   nil,   nil,   129,   nil,   122,   122,   129,   122,   nil,   122,
   nil,   nil,   122,   nil,   129,   129,   122,   nil,   122,   122,
   nil,   122,   122,   122,   122,   122,   nil,   122,   nil,   122,
   nil,   nil,   nil,   122,   nil,   nil,   nil,   nil,   nil,   122,
   nil,    15,    15,   122,    15,    15,    15,   nil,   nil,    15,
   nil,   122,   122,    15,   nil,    15,    15,   nil,    15,    15,
    15,    15,    15,   nil,    15,   nil,    15,   nil,   nil,   nil,
    15,   nil,   nil,   nil,   nil,   nil,    15,   nil,   115,   115,
    15,   115,   nil,   115,   nil,   nil,   115,   nil,    15,    15,
   115,   nil,   115,   115,   nil,   115,   115,   115,   115,   115,
   nil,   115,   nil,   115,   nil,   nil,   nil,   115,   nil,   nil,
   nil,   nil,   nil,   115,   nil,    20,    20,   115,    20,   nil,
    20,   nil,   nil,    20,   115,   115,   115,    20,   nil,    20,
    20,   nil,    20,    20,    20,    20,    20,   nil,    20,   nil,
    20,   nil,   nil,   nil,    20,   nil,   nil,   nil,   nil,   nil,
    20,   nil,   112,   112,    20,   112,   nil,   112,   nil,   nil,
   112,   nil,    20,    20,   112,   nil,   112,   112,   nil,   112,
   112,   112,   112,   112,   nil,   112,   nil,   112,   nil,   nil,
   nil,   112,   nil,   nil,   nil,   nil,   nil,   112,   nil,   nil,
   nil,   112,   nil,   nil,   nil,   nil,   112,   nil,   nil,   112,
   112,   109,   109,   nil,   109,   nil,   109,   nil,   109,   109,
   nil,   nil,   nil,   109,   nil,   109,   109,   nil,   109,   109,
   109,   109,   109,   nil,   109,   nil,   109,   nil,   nil,   nil,
   109,   nil,   nil,   nil,   nil,   nil,   109,   nil,    55,    55,
   109,    55,   nil,    55,   nil,   nil,    55,   nil,   109,   109,
    55,   nil,    55,    55,   nil,    55,    55,    55,    55,    55,
   nil,    55,   nil,    55,   nil,   nil,   nil,    55,   nil,   nil,
    55,   nil,   nil,    55,   nil,     0,     0,    55,     0,   nil,
     0,   nil,   nil,     0,   nil,    55,    55,     0,   nil,     0,
     0,   nil,     0,     0,     0,     0,     0,   nil,     0,   nil,
     0,   nil,   nil,   nil,     0,   nil,   nil,   nil,   nil,   nil,
     0,   nil,     2,     2,     0,     2,   nil,     2,   nil,   nil,
     2,   nil,     0,     0,     2,   nil,     2,     2,   nil,     2,
     2,     2,     2,     2,   nil,     2,   nil,     2,   nil,   nil,
   nil,     2,   nil,   nil,   nil,   nil,   nil,     2,   nil,    36,
    36,     2,    36,   nil,    36,   nil,   nil,    36,   nil,     2,
     2,    36,   nil,    36,    36,   nil,    36,    36,    36,    36,
    36,   nil,    36,   nil,    36,   nil,   nil,   nil,    36,   nil,
   nil,   nil,   nil,   nil,    36,   nil,    90,    90,    36,    90,
   nil,    90,   nil,   nil,    90,   nil,    36,    36,    90,   nil,
    90,    90,   nil,    90,    90,    90,    90,    90,   nil,    90,
   nil,    90,   nil,   nil,   nil,    90,   nil,   nil,   nil,   nil,
    90,    90,   nil,    38,    38,    90,    38,   nil,    38,   nil,
   nil,    38,   nil,    90,    90,    38,    38,    38,    38,   nil,
    38,    38,    38,    38,    38,   nil,    38,   nil,    38,   nil,
   nil,   nil,    38,   nil,   nil,   nil,   nil,   nil,    38,   nil,
    88,    88,    38,    88,   nil,    88,   nil,   nil,    88,   nil,
    38,    38,    88,   nil,    88,    88,   nil,    88,    88,    88,
    88,    88,   nil,    88,   nil,    88,   nil,   nil,   nil,    88,
   nil,   nil,    88,   nil,   nil,    88,   nil,    40,    40,    88,
    40,   nil,    40,   nil,   nil,    40,   nil,    88,    88,    40,
   nil,    40,    40,   nil,    40,    40,    40,    40,    40,   nil,
    40,   nil,    40,   nil,   nil,    40,    40,   nil,   nil,   nil,
   nil,   nil,    40,   nil,   nil,   nil,    40,   nil,    41,    41,
    41,    41,   nil,    41,    40,    40,    41,   nil,   nil,   nil,
    41,   nil,    41,    41,   nil,    41,    41,    41,    41,    41,
   nil,    41,   nil,    41,   nil,   nil,   nil,    41,   nil,   nil,
   nil,   nil,   nil,    41,   nil,    43,    43,    41,    43,   nil,
    43,   nil,   nil,    43,   nil,    41,    41,    43,   nil,    43,
    43,   nil,    43,    43,    43,    43,    43,   nil,    43,   nil,
    43,   nil,   nil,   nil,    43,   nil,   nil,   nil,   nil,   nil,
    43,    43,    86,    86,    43,    86,   nil,    86,   nil,   nil,
    86,   nil,    43,    43,    86,   nil,    86,    86,   nil,    86,
    86,    86,    86,    86,   nil,    86,   nil,    86,   nil,   nil,
   nil,    86,   nil,   nil,   nil,   nil,   nil,    86,   nil,    84,
    84,    86,    84,   nil,    84,   nil,   nil,    84,    86,    86,
    86,    84,   nil,    84,    84,   nil,    84,    84,    84,    84,
    84,   nil,    84,   nil,    84,   nil,   nil,   nil,    84,   nil,
   nil,   nil,   nil,   nil,    84,   nil,    46,    46,    84,    46,
    46,    46,   nil,    84,    46,   nil,    84,    84,    46,   nil,
    46,    46,   nil,    46,    46,    46,    46,    46,   nil,    46,
   nil,    46,   nil,   nil,   nil,    46,   nil,   nil,   nil,   nil,
   nil,    46,   nil,    81,    81,    46,    81,   nil,    81,   nil,
   nil,    81,   nil,    46,    46,    81,   nil,    81,    81,   nil,
    81,    81,    81,    81,    81,   nil,    81,   nil,    81,   nil,
   nil,   nil,    81,   nil,   nil,   nil,   nil,   nil,    81,   nil,
    49,    49,    81,    49,   nil,    49,   nil,   nil,    49,   nil,
    81,    81,    49,   nil,    49,    49,    49,    49,    49,    49,
    49,    49,   nil,    49,   nil,    49,   nil,   nil,   nil,    49,
   nil,   nil,   nil,   nil,   nil,    49,   nil,    71,    71,    49,
    71,   nil,    71,   nil,   nil,    71,   nil,    49,    49,    71,
   nil,    71,    71,   nil,    71,    71,    71,    71,    71,   nil,
    71,   nil,    71,   nil,   nil,   nil,    71,   nil,   nil,   nil,
   nil,   nil,    71,    71,    68,    68,    71,    68,   nil,    68,
   nil,   nil,    68,   nil,    71,    71,    68,   nil,    68,    68,
   nil,    68,    68,    68,    68,    68,   nil,    68,   nil,    68,
   nil,   nil,    68,    68,   nil,   nil,   nil,   nil,   nil,    68,
   nil,    56,    56,    68,    56,   nil,    56,   nil,   nil,    56,
   nil,    68,    68,    56,   nil,    56,    56,   nil,    56,    56,
    56,    56,    56,   nil,    56,   nil,    56,   nil,   nil,   nil,
    56,   nil,   nil,   nil,   nil,    56,    56,   nil,   nil,   nil,
    56,   nil,   146,   146,   nil,   146,   nil,   146,    56,    56,
   146,   nil,   146,   nil,   146,   nil,   146,   146,   nil,   146,
   146,   146,   146,   146,   nil,   146,   nil,   146,   nil,   nil,
   nil,   146,   nil,   nil,   nil,   nil,   nil,   146,   nil,   nil,
   nil,   146,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   146,
   146 ]

racc_action_pointer = [
   513,   nil,   550,   nil,    49,   nil,   nil,    86,    92,   168,
   nil,    76,   nil,   nil,    75,   279,   nil,   nil,   nil,    92,
   353,   nil,   nil,    83,   nil,   nil,     1,   nil,   nil,    -1,
   nil,   nil,   nil,    -2,    77,   nil,   587,    43,   661,    38,
   735,   776,   nil,   813,    -2,    30,   924,   nil,    35,   998,
    27,    19,    73,    77,     8,   476,  1109,    60,    55,    49,
    30,    29,    59,    60,   nil,   nil,    49,   -12,  1072,   nil,
   nil,  1035,   nil,   nil,     0,    15,   nil,    43,    -5,   nil,
   nil,   961,    15,   nil,   887,   -14,   850,    18,   698,   nil,
   624,   nil,    41,   nil,   nil,     6,    -1,    67,    77,    69,
   nil,   nil,    95,   nil,   nil,   nil,   nil,    71,   nil,   439,
   nil,   nil,   390,   -22,    48,   316,   -33,    54,   nil,   nil,
   nil,    89,   242,   nil,    98,   110,   103,   nil,   nil,   205,
   -40,   nil,    75,   -18,   nil,   nil,   109,   127,   111,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,  1150,   nil,   nil,   nil ]

racc_action_default = [
   -80,   -55,    -1,   -36,   -18,   -50,    -2,   -80,   -80,   -80,
    -3,   -22,   -17,    -4,   -80,   -80,   -52,   -10,    -5,   -80,
   -80,    -6,   -38,   -80,    -7,   -51,   -42,   -39,    -8,   -72,
   -54,    -9,   -53,   -80,   -80,   -37,   -19,   -80,   -80,   -62,
   -80,   -80,   -56,   -80,   -22,   -62,   -80,   -57,   -78,   -80,
   -80,   -25,   -42,   -80,   -45,   -80,   -80,   -72,   -80,   -72,
   -80,   -29,   -80,   -80,   -11,   -75,   -80,   -80,   -80,   -65,
   -58,   -80,   -20,   -23,   -22,   -80,   -59,   -80,   -80,   -76,
   -12,   -80,   -80,   -40,   -80,   -45,   -80,   -80,   -80,   -69,
   -80,   -73,   -80,   -68,   -71,   -80,   -80,   -80,   -80,   -31,
   150,   -60,   -64,   -66,   -21,   -24,   -61,   -78,   -77,   -27,
   -26,   -41,   -80,   -45,   -80,   -80,   -45,   -42,   -70,   -74,
   -67,   -29,   -30,   -14,   -33,   -80,   -80,   -63,   -79,   -80,
   -45,   -46,   -42,   -45,   -48,   -43,   -80,   -33,   -80,   -32,
   -15,   -28,   -47,   -44,   -49,   -16,   -33,   -34,   -13,   -35 ]

racc_goto_table = [
    35,    87,    53,     2,    43,    66,    78,    36,   110,   138,
    38,    75,    41,    97,    37,    39,    50,    57,    46,   126,
    58,    45,   147,    49,    34,   nil,   nil,   nil,    82,   nil,
   nil,   149,   114,   nil,    35,   nil,    35,    73,   nil,    35,
   nil,   nil,   nil,    68,    35,   nil,    71,    35,    92,   nil,
    94,   nil,   nil,   nil,   nil,   nil,   141,   nil,    88,    90,
   131,   nil,   nil,   134,   nil,   128,    35,   105,   127,    35,
   nil,   nil,   nil,   136,   102,   nil,   nil,   142,   nil,   nil,
   144,   nil,   nil,   nil,   nil,   nil,    35,   112,    35,   115,
   nil,   nil,   nil,   135,   nil,   nil,   nil,   nil,   nil,   122,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,    35,   143,   nil,
    35,   nil,   nil,    35,   nil,   nil,   nil,   nil,   nil,   nil,
    35,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   146,   nil,   nil,   nil,    35 ]

racc_goto_check = [
     3,    23,    22,     2,    18,    25,    30,     2,    19,    14,
     2,    25,     2,    15,    12,    24,    13,    27,     2,    16,
    28,    24,    14,     2,     1,   nil,   nil,   nil,    22,   nil,
   nil,    14,    23,   nil,     3,   nil,     3,    18,   nil,     3,
   nil,   nil,   nil,     2,     3,   nil,     2,     3,    28,   nil,
    28,   nil,   nil,   nil,   nil,   nil,    19,   nil,     2,     2,
    23,   nil,   nil,    23,   nil,    30,     3,    18,    25,     3,
   nil,   nil,   nil,    15,    24,   nil,   nil,    23,   nil,   nil,
    23,   nil,   nil,   nil,   nil,   nil,     3,     2,     3,     2,
   nil,   nil,   nil,    22,   nil,   nil,   nil,   nil,   nil,     2,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,     3,    22,   nil,
     3,   nil,   nil,     3,   nil,   nil,   nil,   nil,   nil,   nil,
     3,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
     2,   nil,   nil,   nil,     3 ]

racc_goto_pointer = [
   nil,    24,     3,    -2,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,    10,    -7,  -115,   -48,   -80,   nil,    -7,   -73,
   nil,   nil,   -24,   -53,     7,   -34,   nil,   -12,    -9,   nil,
   -42 ]

racc_goto_default = [
   nil,   nil,   109,     3,     6,    10,    13,    18,    21,    24,
    28,    31,   nil,   nil,   nil,   nil,   nil,    12,   nil,   nil,
    22,    27,   nil,   nil,   nil,   nil,    67,   nil,   nil,    59,
   nil ]

racc_reduce_table = [
  0, 0, :racc_error,
  1, 54, :_reduce_1,
  1, 56, :_reduce_2,
  1, 56, :_reduce_3,
  1, 56, :_reduce_4,
  1, 56, :_reduce_5,
  1, 56, :_reduce_6,
  1, 56, :_reduce_7,
  1, 56, :_reduce_8,
  1, 56, :_reduce_9,
  1, 56, :_reduce_10,
  3, 56, :_reduce_11,
  3, 56, :_reduce_12,
  6, 56, :_reduce_13,
  4, 56, :_reduce_14,
  5, 56, :_reduce_15,
  6, 56, :_reduce_16,
  1, 56, :_reduce_none,
  0, 65, :_reduce_18,
  1, 65, :_reduce_19,
  3, 63, :_reduce_20,
  4, 63, :_reduce_21,
  0, 71, :_reduce_22,
  2, 71, :_reduce_23,
  3, 71, :_reduce_24,
  1, 66, :_reduce_25,
  3, 66, :_reduce_26,
  1, 72, :_reduce_27,
  3, 72, :_reduce_28,
  0, 68, :_reduce_29,
  2, 68, :_reduce_30,
  0, 69, :_reduce_31,
  2, 69, :_reduce_32,
  0, 67, :_reduce_33,
  2, 67, :_reduce_34,
  3, 67, :_reduce_35,
  1, 55, :_reduce_36,
  2, 55, :_reduce_37,
  1, 57, :_reduce_38,
  1, 57, :_reduce_39,
  3, 70, :_reduce_40,
  4, 70, :_reduce_41,
  0, 75, :_reduce_42,
  4, 75, :_reduce_43,
  5, 75, :_reduce_44,
  0, 76, :_reduce_45,
  3, 76, :_reduce_46,
  4, 76, :_reduce_47,
  3, 76, :_reduce_48,
  4, 76, :_reduce_49,
  1, 73, :_reduce_50,
  1, 73, :_reduce_51,
  1, 73, :_reduce_52,
  1, 73, :_reduce_53,
  1, 73, :_reduce_54,
  1, 73, :_reduce_55,
  2, 74, :_reduce_56,
  2, 74, :_reduce_57,
  3, 74, :_reduce_58,
  3, 74, :_reduce_59,
  4, 58, :_reduce_60,
  4, 59, :_reduce_61,
  0, 79, :_reduce_62,
  3, 78, :_reduce_63,
  0, 78, :_reduce_64,
  2, 77, :_reduce_65,
  3, 77, :_reduce_66,
  4, 60, :_reduce_67,
  3, 60, :_reduce_68,
  2, 80, :_reduce_69,
  3, 80, :_reduce_70,
  2, 81, :_reduce_71,
  0, 81, :_reduce_72,
  2, 82, :_reduce_73,
  3, 82, :_reduce_74,
  3, 61, :_reduce_75,
  3, 62, :_reduce_76,
  4, 64, :_reduce_77,
  0, 83, :_reduce_78,
  3, 83, :_reduce_79 ]

racc_reduce_n = 80

racc_shift_n = 150

racc_token_table = {
  false => 0,
  :error => 1,
  :TEXT => 2,
  :BOLD_START => 3,
  :BOLD_END => 4,
  :ITALIC_START => 5,
  :ITALIC_END => 6,
  :LINK_START => 7,
  :LINK_END => 8,
  :LINKSEP => 9,
  :INTLINK_START => 10,
  :INTLINK_END => 11,
  :INTLINKSEP => 12,
  :RESOURCESEP => 13,
  :PRE_START => 14,
  :PRE_END => 15,
  :CHAR_ENT => 16,
  :SECTION_START => 17,
  :SECTION_END => 18,
  :HLINE => 19,
  :SIGNATURE_NAME => 20,
  :SIGNATURE_DATE => 21,
  :SIGNATURE_FULL => 22,
  :PARA_START => 23,
  :PARA_END => 24,
  :UL_START => 25,
  :UL_END => 26,
  :OL_START => 27,
  :OL_END => 28,
  :LI_START => 29,
  :LI_END => 30,
  :DL_START => 31,
  :DL_END => 32,
  :DT_START => 33,
  :DT_END => 34,
  :DD_START => 35,
  :DD_END => 36,
  :TAG_START => 37,
  :TAG_END => 38,
  :ATTR_NAME => 39,
  :ATTR_VALUE => 40,
  :TABLE_START => 41,
  :TABLE_END => 42,
  :ROW_START => 43,
  :ROW_END => 44,
  :HEAD_START => 45,
  :HEAD_END => 46,
  :CELL_START => 47,
  :CELL_END => 48,
  :KEYWORD => 49,
  :TEMPLATE_START => 50,
  :TEMPLATE_END => 51,
  :CATEGORY => 52 }

racc_nt_base = 53

racc_use_result_var = true

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]

Racc_token_to_s_table = [
  "$end",
  "error",
  "TEXT",
  "BOLD_START",
  "BOLD_END",
  "ITALIC_START",
  "ITALIC_END",
  "LINK_START",
  "LINK_END",
  "LINKSEP",
  "INTLINK_START",
  "INTLINK_END",
  "INTLINKSEP",
  "RESOURCESEP",
  "PRE_START",
  "PRE_END",
  "CHAR_ENT",
  "SECTION_START",
  "SECTION_END",
  "HLINE",
  "SIGNATURE_NAME",
  "SIGNATURE_DATE",
  "SIGNATURE_FULL",
  "PARA_START",
  "PARA_END",
  "UL_START",
  "UL_END",
  "OL_START",
  "OL_END",
  "LI_START",
  "LI_END",
  "DL_START",
  "DL_END",
  "DT_START",
  "DT_END",
  "DD_START",
  "DD_END",
  "TAG_START",
  "TAG_END",
  "ATTR_NAME",
  "ATTR_VALUE",
  "TABLE_START",
  "TABLE_END",
  "ROW_START",
  "ROW_END",
  "HEAD_START",
  "HEAD_END",
  "CELL_START",
  "CELL_END",
  "KEYWORD",
  "TEMPLATE_START",
  "TEMPLATE_END",
  "CATEGORY",
  "$start",
  "wiki",
  "repeated_contents",
  "contents",
  "text",
  "bulleted_list",
  "numbered_list",
  "dictionary_list",
  "preformatted",
  "section",
  "tag",
  "template",
  "para_contents",
  "link_contents",
  "reslink_repeated_contents",
  "intlink_repeated_contents",
  "cat_sort_contents",
  "table",
  "tag_attributes",
  "link_repeated_contents",
  "element",
  "formatted_element",
  "table_contents",
  "row_contents",
  "list_item",
  "list_contents",
  "@1",
  "dictionary_term",
  "dictionary_contents",
  "dictionary_definition",
  "template_parameters" ]

Racc_debug_parser = false

##### State transition tables end #####

# reduce 0 omitted

module_eval(<<'.,.,', 'mediawikiparser.y', 24)
  def _reduce_1(val, _values, result)
                @nodes.push WikiAST.new
            #@nodes.last.children.insert(0, val[0])
            #puts val[0]
            @nodes.last.children += val[0]
        
    result
  end
.,.,

module_eval(<<'.,.,', 'mediawikiparser.y', 34)
  def _reduce_2(val, _values, result)
                result = val[0]
        
    result
  end
.,.,

module_eval(<<'.,.,', 'mediawikiparser.y', 38)
  def _reduce_3(val, _values, result)
                result = val[0]
        
    result
  end
.,.,

module_eval(<<'.,.,', 'mediawikiparser.y', 42)
  def _reduce_4(val, _values, result)
                result = val[0]
        
    result
  end
.,.,

module_eval(<<'.,.,', 'mediawikiparser.y', 46)
  def _reduce_5(val, _values, result)
                list = ListAST.new
            list.list_type = :Dictionary
            list.children = val[0]
            result = list
        
    result
  end
.,.,

module_eval(<<'.,.,', 'mediawikiparser.y', 53)
  def _reduce_6(val, _values, result)
                result = val[0]
        
    result
  end
.,.,

module_eval(<<'.,.,', 'mediawikiparser.y', 57)
  def _reduce_7(val, _values, result)
                result = val[0]
        
    result
  end
.,.,

module_eval(<<'.,.,', 'mediawikiparser.y', 61)
  def _reduce_8(val, _values, result)
                result = val[0]
        
    result
  end
.,.,

module_eval(<<'.,.,', 'mediawikiparser.y', 65)
  def _reduce_9(val, _values, result)
                result = val[0]
        
    result
  end
.,.,

module_eval(<<'.,.,', 'mediawikiparser.y', 69)
  def _reduce_10(val, _values, result)
                k = KeywordAST.new
            k.text = val[0]
            result = k
        
    result
  end
.,.,

module_eval(<<'.,.,', 'mediawikiparser.y', 75)
  def _reduce_11(val, _values, result)
                p = ParagraphAST.new
            p.children = val[1]
            result = p
        
    result
  end
.,.,

module_eval(<<'.,.,', 'mediawikiparser.y', 81)
  def _reduce_12(val, _values, result)
                l = LinkAST.new
            l.url = val[1][0]
            l.children += val[1][1..-1] if val[1].length > 1
            result = l
        
    result
  end
.,.,

module_eval(<<'.,.,', 'mediawikiparser.y', 88)
  def _reduce_13(val, _values, result)
                l = ResourceLinkAST.new
            l.prefix = val[1]
            l.locator = val[3]
            l.children = val[4] unless val[4].nil? or val[4].empty?
            result = l
        
    result
  end
.,.,

module_eval(<<'.,.,', 'mediawikiparser.y', 96)
  def _reduce_14(val, _values, result)
                l = InternalLinkAST.new
            l.locator = val[1]
            l.children = val[2] unless val[2].nil? or val[2].empty?
            result = l
        
    result
  end
.,.,

module_eval(<<'.,.,', 'mediawikiparser.y', 103)
  def _reduce_15(val, _values, result)
                l = CategoryAST.new
            l.locator = val[2]
            l.sort_as = val[3]
            result = l
        
    result
  end
.,.,

module_eval(<<'.,.,', 'mediawikiparser.y', 110)
  def _reduce_16(val, _values, result)
                l = CategoryLinkAST.new
            l.locator = val[3]
            l.children = val[4] unless val[4].nil? or val[4].empty?
            result = l
        
    result
  end
.,.,

# reduce 17 omitted

module_eval(<<'.,.,', 'mediawikiparser.y', 120)
  def _reduce_18(val, _values, result)
                result = nil
        
    result
  end
.,.,

module_eval(<<'.,.,', 'mediawikiparser.y', 124)
  def _reduce_19(val, _values, result)
                result = val[0]
        
    result
  end
.,.,

module_eval(<<'.,.,', 'mediawikiparser.y', 131)
  def _reduce_20(val, _values, result)
                if val[0] != val[2] 
                raise Racc::ParseError.new("XHTML end tag #{val[2]} does not match start tag #{val[0]}")
            end
            elem = ElementAST.new
            elem.name = val[0]
            elem.attributes = val[1]
            result = elem
        
    result
  end
.,.,

module_eval(<<'.,.,', 'mediawikiparser.y', 141)
  def _reduce_21(val, _values, result)
                if val[0] != val[3] 
                raise Racc::ParseError.new("XHTML end tag #{val[3]} does not match start tag #{val[0]}")
            end
            elem = ElementAST.new
            elem.name = val[0]
            elem.attributes = val[1]
            elem.children += val[2]
            result = elem
        
    result
  end
.,.,

module_eval(<<'.,.,', 'mediawikiparser.y', 154)
  def _reduce_22(val, _values, result)
                result = nil
        
    result
  end
.,.,

module_eval(<<'.,.,', 'mediawikiparser.y', 158)
  def _reduce_23(val, _values, result)
                attr_map = val[2] ? val[2] : {}
            attr_map[val[0]] = true
            result = attr_map 
        
    result
  end
.,.,

module_eval(<<'.,.,', 'mediawikiparser.y', 164)
  def _reduce_24(val, _values, result)
                attr_map = val[2] ? val[2] : {}
            attr_map[val[0]] = val[1]
            result = attr_map 
        
    result
  end
.,.,

module_eval(<<'.,.,', 'mediawikiparser.y', 174)
  def _reduce_25(val, _values, result)
                result = val
        
    result
  end
.,.,

module_eval(<<'.,.,', 'mediawikiparser.y', 178)
  def _reduce_26(val, _values, result)
                result = [val[0]]
            result += val[2]
        
    result
  end
.,.,

module_eval(<<'.,.,', 'mediawikiparser.y', 187)
  def _reduce_27(val, _values, result)
                result = val[0]
        
    result
  end
.,.,

module_eval(<<'.,.,', 'mediawikiparser.y', 191)
  def _reduce_28(val, _values, result)
                result = val[0]
            result += val[2] if val[2]
        
    result
  end
.,.,

module_eval(<<'.,.,', 'mediawikiparser.y', 199)
  def _reduce_29(val, _values, result)
                result = nil
        
    result
  end
.,.,

module_eval(<<'.,.,', 'mediawikiparser.y', 203)
  def _reduce_30(val, _values, result)
                result = val[1]
        
    result
  end
.,.,

module_eval(<<'.,.,', 'mediawikiparser.y', 209)
  def _reduce_31(val, _values, result)
                result = nil
        
    result
  end
.,.,

module_eval(<<'.,.,', 'mediawikiparser.y', 213)
  def _reduce_32(val, _values, result)
                result = val[1]
        
    result
  end
.,.,

module_eval(<<'.,.,', 'mediawikiparser.y', 219)
  def _reduce_33(val, _values, result)
                result = nil
        
    result
  end
.,.,

module_eval(<<'.,.,', 'mediawikiparser.y', 223)
  def _reduce_34(val, _values, result)
                result = val[1]
        
    result
  end
.,.,

module_eval(<<'.,.,', 'mediawikiparser.y', 227)
  def _reduce_35(val, _values, result)
                i = InternalLinkItemAST.new
            i.children = val[1]
            result = [i]
            result += val[2] if val[2]
        
    result
  end
.,.,

module_eval(<<'.,.,', 'mediawikiparser.y', 236)
  def _reduce_36(val, _values, result)
                result = []
            result << val[0]
        
    result
  end
.,.,

module_eval(<<'.,.,', 'mediawikiparser.y', 241)
  def _reduce_37(val, _values, result)
                result = []
            result += val[0]
            result << val[1]
        
    result
  end
.,.,

module_eval(<<'.,.,', 'mediawikiparser.y', 249)
  def _reduce_38(val, _values, result)
                p = TextAST.new
            p.formatting = val[0][0]
            p.contents = val[0][1]
            result = p
        
    result
  end
.,.,

module_eval(<<'.,.,', 'mediawikiparser.y', 256)
  def _reduce_39(val, _values, result)
                result = val[0]
        
    result
  end
.,.,

module_eval(<<'.,.,', 'mediawikiparser.y', 263)
  def _reduce_40(val, _values, result)
                table = TableAST.new
            table.children = val[1] unless val[1].nil? or val[1].empty?
            result = table
        
    result
  end
.,.,

module_eval(<<'.,.,', 'mediawikiparser.y', 269)
  def _reduce_41(val, _values, result)
                table = TableAST.new
            table.options = val[1]
            table.children = val[2] unless val[2].nil? or val[2].empty?
            result = table
        
    result
  end
.,.,

module_eval(<<'.,.,', 'mediawikiparser.y', 277)
  def _reduce_42(val, _values, result)
                result = nil
        
    result
  end
.,.,

module_eval(<<'.,.,', 'mediawikiparser.y', 281)
  def _reduce_43(val, _values, result)
                row = TableRowAST.new
            row.children = val[1] unless val[1].nil? or val[1].empty?
            result = [row]
            result += val[3] unless val[3].nil? or val[3].empty?
        
    result
  end
.,.,

module_eval(<<'.,.,', 'mediawikiparser.y', 288)
  def _reduce_44(val, _values, result)
                row = TableRowAST.new
            row.children = val[2] unless val[2].nil? or val[2].empty?
            row.options = val[1]
            result = [row]
            result += val[4] unless val[4].nil? or val[4].empty?
        
    result
  end
.,.,

module_eval(<<'.,.,', 'mediawikiparser.y', 297)
  def _reduce_45(val, _values, result)
                result = nil
        
    result
  end
.,.,

module_eval(<<'.,.,', 'mediawikiparser.y', 301)
  def _reduce_46(val, _values, result)
                cell = TableCellAST.new
            cell.type = :head
            result = [cell]
            result += val[2] unless val[2].nil? or val[2].empty?
        
    result
  end
.,.,

module_eval(<<'.,.,', 'mediawikiparser.y', 308)
  def _reduce_47(val, _values, result)
                cell = TableCellAST.new
            cell.children = val[1] unless val[1].nil? or val[1].empty?
            cell.type = :head
            result = [cell]
            result += val[3] unless val[3].nil? or val[3].empty?
        
    result
  end
.,.,

module_eval(<<'.,.,', 'mediawikiparser.y', 316)
  def _reduce_48(val, _values, result)
                cell = TableCellAST.new
            cell.type = :body
            result = [cell]
            result += val[2] unless val[2].nil? or val[2].empty?
        
    result
  end
.,.,

module_eval(<<'.,.,', 'mediawikiparser.y', 323)
  def _reduce_49(val, _values, result)
                cell = TableCellAST.new
            cell.children = val[1] unless val[1].nil? or val[1].empty?
            cell.type = :body
            result = [cell]
            result += val[3] unless val[3].nil? or val[3].empty?
        
    result
  end
.,.,

module_eval(<<'.,.,', 'mediawikiparser.y', 333)
  def _reduce_50(val, _values, result)
     return [:None, val[0]] 
    result
  end
.,.,

module_eval(<<'.,.,', 'mediawikiparser.y', 335)
  def _reduce_51(val, _values, result)
     return [:HLine, val[0]] 
    result
  end
.,.,

module_eval(<<'.,.,', 'mediawikiparser.y', 337)
  def _reduce_52(val, _values, result)
     return [:CharacterEntity, val[0]] 
    result
  end
.,.,

module_eval(<<'.,.,', 'mediawikiparser.y', 339)
  def _reduce_53(val, _values, result)
     return [:SignatureDate, val[0]] 
    result
  end
.,.,

module_eval(<<'.,.,', 'mediawikiparser.y', 341)
  def _reduce_54(val, _values, result)
     return [:SignatureName, val[0]] 
    result
  end
.,.,

module_eval(<<'.,.,', 'mediawikiparser.y', 343)
  def _reduce_55(val, _values, result)
     return [:SignatureFull, val[0]] 
    result
  end
.,.,

module_eval(<<'.,.,', 'mediawikiparser.y', 349)
  def _reduce_56(val, _values, result)
                result = FormattedAST.new
            result.formatting = :Bold
            result
        
    result
  end
.,.,

module_eval(<<'.,.,', 'mediawikiparser.y', 355)
  def _reduce_57(val, _values, result)
                result = FormattedAST.new
            result.formatting = :Italic
            result
        
    result
  end
.,.,

module_eval(<<'.,.,', 'mediawikiparser.y', 361)
  def _reduce_58(val, _values, result)
                p = FormattedAST.new
            p.formatting = :Bold
            p.children += val[1]
            result = p
        
    result
  end
.,.,

module_eval(<<'.,.,', 'mediawikiparser.y', 368)
  def _reduce_59(val, _values, result)
                p = FormattedAST.new
            p.formatting = :Italic
            p.children += val[1]
            result = p
        
    result
  end
.,.,

module_eval(<<'.,.,', 'mediawikiparser.y', 377)
  def _reduce_60(val, _values, result)
                list = ListAST.new
            list.list_type = :Bulleted
            list.children << val[1]
            list.children += val[2]
            result = list
        
    result
  end
.,.,

module_eval(<<'.,.,', 'mediawikiparser.y', 387)
  def _reduce_61(val, _values, result)
                list = ListAST.new
            list.list_type = :Numbered
            list.children << val[1]
            list.children += val[2]
            result = list
        
    result
  end
.,.,

module_eval(<<'.,.,', 'mediawikiparser.y', 396)
  def _reduce_62(val, _values, result)
     result = [] 
    result
  end
.,.,

module_eval(<<'.,.,', 'mediawikiparser.y', 399)
  def _reduce_63(val, _values, result)
                result << val[1]
            result += val[2]
        
    result
  end
.,.,

module_eval(<<'.,.,', 'mediawikiparser.y', 403)
  def _reduce_64(val, _values, result)
     result = [] 
    result
  end
.,.,

module_eval(<<'.,.,', 'mediawikiparser.y', 409)
  def _reduce_65(val, _values, result)
                result = ListItemAST.new
        
    result
  end
.,.,

module_eval(<<'.,.,', 'mediawikiparser.y', 413)
  def _reduce_66(val, _values, result)
                li = ListItemAST.new
            li.children += val[1]
            result = li
        
    result
  end
.,.,

module_eval(<<'.,.,', 'mediawikiparser.y', 422)
  def _reduce_67(val, _values, result)
                result = [val[1]]
            result += val[2]
        
    result
  end
.,.,

module_eval(<<'.,.,', 'mediawikiparser.y', 427)
  def _reduce_68(val, _values, result)
                result = val[1]
        
    result
  end
.,.,

module_eval(<<'.,.,', 'mediawikiparser.y', 434)
  def _reduce_69(val, _values, result)
                result = ListTermAST.new
        
    result
  end
.,.,

module_eval(<<'.,.,', 'mediawikiparser.y', 438)
  def _reduce_70(val, _values, result)
                term = ListTermAST.new
            term.children += val[1]
            result = term
        
    result
  end
.,.,

module_eval(<<'.,.,', 'mediawikiparser.y', 446)
  def _reduce_71(val, _values, result)
                result = [val[0]]
            result += val[1] if val[1]
        
    result
  end
.,.,

module_eval(<<'.,.,', 'mediawikiparser.y', 451)
  def _reduce_72(val, _values, result)
                result = []
        
    result
  end
.,.,

module_eval(<<'.,.,', 'mediawikiparser.y', 457)
  def _reduce_73(val, _values, result)
                result = ListDefinitionAST.new
        
    result
  end
.,.,

module_eval(<<'.,.,', 'mediawikiparser.y', 461)
  def _reduce_74(val, _values, result)
                term = ListDefinitionAST.new
            term.children += val[1]
            result = term
        
    result
  end
.,.,

module_eval(<<'.,.,', 'mediawikiparser.y', 468)
  def _reduce_75(val, _values, result)
                p = PreformattedAST.new
            p.children += val[1]
            result = p
        
    result
  end
.,.,

module_eval(<<'.,.,', 'mediawikiparser.y', 475)
  def _reduce_76(val, _values, result)
     result = [val[1], val[0].length] 
            s = SectionAST.new
            s.children = val[1]
            s.level = val[0].length
            result = s
        
    result
  end
.,.,

module_eval(<<'.,.,', 'mediawikiparser.y', 485)
  def _reduce_77(val, _values, result)
                t = TemplateAST.new
            t.template_name = val[1]
            t.children = val[2] unless val[2].nil? or val[2].empty?
            result = t
        
    result
  end
.,.,

module_eval(<<'.,.,', 'mediawikiparser.y', 494)
  def _reduce_78(val, _values, result)
                result = nil
        
    result
  end
.,.,

module_eval(<<'.,.,', 'mediawikiparser.y', 498)
  def _reduce_79(val, _values, result)
                p = TemplateParameterAST.new
            p.children = val[1]
            result = [p]
            result += val[2] if val[2]
        
    result
  end
.,.,

def _reduce_none(val, _values, result)
  val[0]
end

end   # class MediaWikiParser
