#
# DO NOT MODIFY!!!!
# This file is automatically generated by racc 1.4.5
# from racc grammer file "mediawikiparser.y".
#

require 'racc/parser'


require 'mediawikiast'


class MediaWikiParser < Racc::Parser

module_eval <<'..end mediawikiparser.y modeval..id413cf46e52', 'mediawikiparser.y', 138

attr_accessor :lexer

def initialize
    @nodes = []
    super
end

#Tokenizes input string and parses it.
#--
#TODO: return AST here
#++
def parse(input)
    @yydebug=true
    lexer.tokenize(input)
    do_parse
    return @nodes.last
end

#Asks the lexer to return the next token.
def next_token
    return @lexer.lex
end
..end mediawikiparser.y modeval..id413cf46e52

##### racc 1.4.5 generates ###

racc_reduce_table = [
 0, 0, :racc_error,
 0, 24, :_reduce_1,
 3, 22, :_reduce_2,
 0, 22, :_reduce_none,
 1, 23, :_reduce_4,
 1, 23, :_reduce_5,
 1, 23, :_reduce_6,
 1, 23, :_reduce_7,
 0, 31, :_reduce_8,
 3, 29, :_reduce_9,
 0, 32, :_reduce_10,
 3, 30, :_reduce_11,
 0, 30, :_reduce_12,
 1, 25, :_reduce_13,
 3, 33, :_reduce_14,
 3, 33, :_reduce_15,
 3, 33, :_reduce_16,
 3, 33, :_reduce_17,
 1, 33, :_reduce_18,
 1, 33, :_reduce_19,
 4, 26, :_reduce_20,
 0, 36, :_reduce_21,
 3, 35, :_reduce_22,
 0, 35, :_reduce_23,
 3, 34, :_reduce_24,
 1, 27, :_reduce_25,
 3, 28, :_reduce_26 ]

racc_reduce_n = 27

racc_shift_n = 46

racc_action_table = [
     7,     8,    11,    29,    14,    -3,    16,    17,    18,     4,
     7,     8,    11,    10,    14,    21,    16,    17,    18,     4,
     7,     8,    11,    10,    14,    22,    16,    17,    18,     4,
    24,    25,    26,    10,    27,    28,    19,   -23,    34,    35,
    36,    37,    24,    39,    -3,   -23,   -12,     3,   -12 ]

racc_action_check = [
     2,     2,     2,    22,     2,     6,     2,     2,     2,     2,
    43,    43,    43,     2,    43,     7,    43,    43,    43,    43,
    33,    33,    33,    43,    33,     8,    33,    33,    33,    33,
    10,    11,    14,    33,    16,    21,     3,    23,    25,    26,
    27,    30,    31,    32,     0,    38,    40,     1,    44 ]

racc_action_pointer = [
    44,    47,    -2,    36,   nil,   nil,     5,     6,    16,   nil,
    13,    22,   nil,   nil,    23,   nil,    25,   nil,   nil,   nil,
   nil,    33,     0,    21,   nil,    33,    32,    32,   nil,   nil,
    25,    25,    25,    18,   nil,   nil,   nil,   nil,    29,   nil,
    28,   nil,   nil,     8,    30,   nil ]

racc_action_default = [
    -1,   -27,   -27,   -27,   -19,   -13,    -1,   -27,   -27,    -4,
   -27,   -27,    -5,    -6,   -27,    -7,   -27,   -18,   -25,    46,
    -2,   -27,   -27,   -21,    -8,   -27,   -27,   -27,   -14,   -15,
   -27,   -27,   -27,   -27,   -16,   -17,   -26,   -20,   -21,   -24,
   -10,   -22,    -9,   -27,   -10,   -11 ]

racc_goto_table = [
     6,    23,    30,     1,    42,    32,    33,   nil,    45,    20,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,    41,   nil,   nil,
   nil,   nil,    38,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,    40,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,    44 ]

racc_goto_check = [
     2,    13,    14,     1,     9,     8,    10,   nil,     9,     1,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,    14,   nil,   nil,
   nil,   nil,    13,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,     2,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,     2 ]

racc_goto_pointer = [
   nil,     3,    -2,   nil,   nil,   nil,   nil,   nil,   -19,   -36,
   -18,   nil,   nil,    -9,   -21,   nil ]

racc_goto_default = [
   nil,   nil,   nil,     2,     9,    12,    13,    15,   nil,   nil,
   nil,    43,     5,   nil,   nil,    31 ]

racc_token_table = {
 false => 0,
 Object.new => 1,
 :BOLD => 2,
 :ITALIC => 3,
 :LINKSTART => 4,
 :LINKEND => 5,
 :INTLINKSTART => 6,
 :INTLINKEND => 7,
 :SECTION => 8,
 :TEXT => 9,
 :PRE => 10,
 :HLINE => 11,
 :SIGNATURE_NAME => 12,
 :SIGNATURE_DATE => 13,
 :SIGNATURE_FULL => 14,
 :UL_START => 15,
 :UL_END => 16,
 :LI_START => 17,
 :LI_END => 18,
 :OL_START => 19,
 :OL_END => 20 }

racc_use_result_var = true

racc_nt_base = 21

Racc_arg = [
 racc_action_table,
 racc_action_check,
 racc_action_default,
 racc_action_pointer,
 racc_goto_table,
 racc_goto_check,
 racc_goto_default,
 racc_goto_pointer,
 racc_nt_base,
 racc_reduce_table,
 racc_token_table,
 racc_shift_n,
 racc_reduce_n,
 racc_use_result_var ]

Racc_token_to_s_table = [
'$end',
'error',
'BOLD',
'ITALIC',
'LINKSTART',
'LINKEND',
'INTLINKSTART',
'INTLINKEND',
'SECTION',
'TEXT',
'PRE',
'HLINE',
'SIGNATURE_NAME',
'SIGNATURE_DATE',
'SIGNATURE_FULL',
'UL_START',
'UL_END',
'LI_START',
'LI_END',
'OL_START',
'OL_END',
'$start',
'wiki',
'contents',
'@1',
'text',
'bulleted_list',
'preformatted',
'section',
'repeated_contents',
'repeated_contents_cont',
'@2',
'@3',
'element',
'list_item',
'list_contents',
'@4']

Racc_debug_parser = false

##### racc system variables end #####

 # reduce 0 omitted

module_eval <<'.,.,', 'mediawikiparser.y', 21
  def _reduce_1( val, _values, result )
            @nodes.push WikiAST.new
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 25
  def _reduce_2( val, _values, result )
            @nodes.last.children.insert(0, val[1])
   result
  end
.,.,

 # reduce 3 omitted

module_eval <<'.,.,', 'mediawikiparser.y', 33
  def _reduce_4( val, _values, result )
            result = val[0]
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 37
  def _reduce_5( val, _values, result )
            result = val[0]
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 43
  def _reduce_6( val, _values, result )
            p = PreformattedAST.new
            p.contents = val[0]
            result = p
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 49
  def _reduce_7( val, _values, result )
            s = SectionAST.new
            s.contents = val[0]
            result = s
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 52
  def _reduce_8( val, _values, result )
 result = []
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 58
  def _reduce_9( val, _values, result )
            result << val[1]
            result += val[2]
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 61
  def _reduce_10( val, _values, result )
 result = []
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 67
  def _reduce_11( val, _values, result )
            result << val[1]
            result += val[2]
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 68
  def _reduce_12( val, _values, result )
 result = []
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 78
  def _reduce_13( val, _values, result )
            p = TextAST.new
            p.formatting = val[0][0]
            p.contents = val[0][1]
            result = p
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 81
  def _reduce_14( val, _values, result )
 return [:Bold, val[1]]
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 83
  def _reduce_15( val, _values, result )
 return [:Italic, val[1]]
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 85
  def _reduce_16( val, _values, result )
 return [:Link, val[1]]
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 87
  def _reduce_17( val, _values, result )
 return [:InternalLink, val[1]]
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 89
  def _reduce_18( val, _values, result )
 return [:None, val[0]]
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 91
  def _reduce_19( val, _values, result )
 return [:HLine, val[0]]
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 102
  def _reduce_20( val, _values, result )
            list = ListAST.new
            list.type = :Bulleted
            list.children << val[1]
            list.children += val[2]
            result = list
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 105
  def _reduce_21( val, _values, result )
 result = []
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 111
  def _reduce_22( val, _values, result )
            result << val[1]
            result += val[2]
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 112
  def _reduce_23( val, _values, result )
 result = []
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 121
  def _reduce_24( val, _values, result )
            li = ListItemAST.new
            li.children += val[1]
            result = li
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 124
  def _reduce_25( val, _values, result )
 result = val[0]
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 128
  def _reduce_26( val, _values, result )
 result = val[1]
   result
  end
.,.,

 def _reduce_none( val, _values, result )
  result
 end

end   # class MediaWikiParser
