#
# DO NOT MODIFY!!!!
# This file is automatically generated by racc 1.4.5
# from racc grammer file "mediawikiparser.y".
#

require 'racc/parser'


require 'mediawikiast'


class MediaWikiParser < Racc::Parser

module_eval <<'..end mediawikiparser.y modeval..id6a5e4b9e09', 'mediawikiparser.y', 144

attr_accessor :lexer

def initialize
    @nodes = []
    super
end

#Tokenizes input string and parses it.
#--
#TODO: return AST here
#++
def parse(input)
    @yydebug=true
    lexer.tokenize(input)
    do_parse
    return @nodes.last
end

#Asks the lexer to return the next token.
def next_token
    return @lexer.lex
end
..end mediawikiparser.y modeval..id6a5e4b9e09

##### racc 1.4.5 generates ###

racc_reduce_table = [
 0, 0, :racc_error,
 0, 24, :_reduce_1,
 3, 22, :_reduce_2,
 0, 22, :_reduce_none,
 1, 23, :_reduce_4,
 1, 23, :_reduce_5,
 1, 23, :_reduce_6,
 1, 23, :_reduce_7,
 0, 31, :_reduce_8,
 3, 29, :_reduce_9,
 0, 32, :_reduce_10,
 3, 30, :_reduce_11,
 0, 30, :_reduce_12,
 1, 25, :_reduce_13,
 3, 33, :_reduce_14,
 3, 33, :_reduce_15,
 3, 33, :_reduce_16,
 3, 33, :_reduce_17,
 1, 33, :_reduce_18,
 1, 33, :_reduce_19,
 1, 33, :_reduce_20,
 1, 33, :_reduce_21,
 1, 33, :_reduce_22,
 4, 26, :_reduce_23,
 0, 36, :_reduce_24,
 3, 35, :_reduce_25,
 0, 35, :_reduce_26,
 3, 34, :_reduce_27,
 1, 27, :_reduce_28,
 3, 28, :_reduce_29 ]

racc_reduce_n = 30

racc_shift_n = 49

racc_action_table = [
     9,    11,    14,    32,    17,    -3,    19,    20,    21,     4,
     6,     8,    10,    13,     9,    11,    14,    24,    17,    25,
    19,    20,    21,     4,     6,     8,    10,    13,     9,    11,
    14,    27,    17,    28,    19,    20,    21,     4,     6,     8,
    10,    13,    29,    30,    31,    22,   -26,    37,    38,    39,
    40,    27,    42,    -3,   -26,   -12,     3,   -12 ]

racc_action_check = [
     2,     2,     2,    25,     2,     7,     2,     2,     2,     2,
     2,     2,     2,     2,    46,    46,    46,     9,    46,    11,
    46,    46,    46,    46,    46,    46,    46,    46,    36,    36,
    36,    13,    36,    14,    36,    36,    36,    36,    36,    36,
    36,    36,    17,    19,    24,     3,    26,    28,    29,    30,
    33,    34,    35,     0,    41,    43,     1,    47 ]

racc_action_pointer = [
    53,    56,    -2,    45,   nil,   nil,   nil,     5,   nil,     8,
   nil,    10,   nil,    14,    24,   nil,   nil,    33,   nil,    34,
   nil,   nil,   nil,   nil,    42,     0,    30,   nil,    42,    41,
    41,   nil,   nil,    34,    34,    34,    26,   nil,   nil,   nil,
   nil,    38,   nil,    37,   nil,   nil,    12,    39,   nil ]

racc_action_default = [
    -1,   -30,   -30,   -30,   -19,   -13,   -21,    -1,   -20,   -30,
   -22,   -30,    -4,   -30,   -30,    -5,    -6,   -30,    -7,   -30,
   -18,   -28,    49,    -2,   -30,   -30,   -24,    -8,   -30,   -30,
   -30,   -14,   -15,   -30,   -30,   -30,   -30,   -16,   -17,   -29,
   -23,   -24,   -27,   -10,   -25,    -9,   -30,   -10,   -11 ]

racc_goto_table = [
     7,    26,    33,     1,    45,    35,    36,   nil,    48,   nil,
    23,   nil,   nil,   nil,   nil,   nil,   nil,    44,   nil,   nil,
   nil,   nil,    41,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,    43,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,    47 ]

racc_goto_check = [
     2,    13,    14,     1,     9,     8,    10,   nil,     9,   nil,
     1,   nil,   nil,   nil,   nil,   nil,   nil,    14,   nil,   nil,
   nil,   nil,    13,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,     2,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,     2 ]

racc_goto_pointer = [
   nil,     3,    -2,   nil,   nil,   nil,   nil,   nil,   -22,   -39,
   -21,   nil,   nil,   -12,   -24,   nil ]

racc_goto_default = [
   nil,   nil,   nil,     2,    12,    15,    16,    18,   nil,   nil,
   nil,    46,     5,   nil,   nil,    34 ]

racc_token_table = {
 false => 0,
 Object.new => 1,
 :BOLD => 2,
 :ITALIC => 3,
 :LINKSTART => 4,
 :LINKEND => 5,
 :INTLINKSTART => 6,
 :INTLINKEND => 7,
 :SECTION => 8,
 :TEXT => 9,
 :PRE => 10,
 :HLINE => 11,
 :SIGNATURE_NAME => 12,
 :SIGNATURE_DATE => 13,
 :SIGNATURE_FULL => 14,
 :UL_START => 15,
 :UL_END => 16,
 :LI_START => 17,
 :LI_END => 18,
 :OL_START => 19,
 :OL_END => 20 }

racc_use_result_var = true

racc_nt_base = 21

Racc_arg = [
 racc_action_table,
 racc_action_check,
 racc_action_default,
 racc_action_pointer,
 racc_goto_table,
 racc_goto_check,
 racc_goto_default,
 racc_goto_pointer,
 racc_nt_base,
 racc_reduce_table,
 racc_token_table,
 racc_shift_n,
 racc_reduce_n,
 racc_use_result_var ]

Racc_token_to_s_table = [
'$end',
'error',
'BOLD',
'ITALIC',
'LINKSTART',
'LINKEND',
'INTLINKSTART',
'INTLINKEND',
'SECTION',
'TEXT',
'PRE',
'HLINE',
'SIGNATURE_NAME',
'SIGNATURE_DATE',
'SIGNATURE_FULL',
'UL_START',
'UL_END',
'LI_START',
'LI_END',
'OL_START',
'OL_END',
'$start',
'wiki',
'contents',
'@1',
'text',
'bulleted_list',
'preformatted',
'section',
'repeated_contents',
'repeated_contents_cont',
'@2',
'@3',
'element',
'list_item',
'list_contents',
'@4']

Racc_debug_parser = false

##### racc system variables end #####

 # reduce 0 omitted

module_eval <<'.,.,', 'mediawikiparser.y', 21
  def _reduce_1( val, _values, result )
            @nodes.push WikiAST.new
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 25
  def _reduce_2( val, _values, result )
            @nodes.last.children.insert(0, val[1])
   result
  end
.,.,

 # reduce 3 omitted

module_eval <<'.,.,', 'mediawikiparser.y', 33
  def _reduce_4( val, _values, result )
            result = val[0]
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 37
  def _reduce_5( val, _values, result )
            result = val[0]
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 43
  def _reduce_6( val, _values, result )
            p = PreformattedAST.new
            p.contents = val[0]
            result = p
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 49
  def _reduce_7( val, _values, result )
            s = SectionAST.new
            s.contents = val[0]
            result = s
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 52
  def _reduce_8( val, _values, result )
 result = []
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 58
  def _reduce_9( val, _values, result )
            result << val[1]
            result += val[2]
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 61
  def _reduce_10( val, _values, result )
 result = []
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 67
  def _reduce_11( val, _values, result )
            result << val[1]
            result += val[2]
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 68
  def _reduce_12( val, _values, result )
 result = []
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 78
  def _reduce_13( val, _values, result )
            p = TextAST.new
            p.formatting = val[0][0]
            p.contents = val[0][1]
            result = p
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 81
  def _reduce_14( val, _values, result )
 return [:Bold, val[1]]
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 83
  def _reduce_15( val, _values, result )
 return [:Italic, val[1]]
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 85
  def _reduce_16( val, _values, result )
 return [:Link, val[1]]
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 87
  def _reduce_17( val, _values, result )
 return [:InternalLink, val[1]]
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 89
  def _reduce_18( val, _values, result )
 return [:None, val[0]]
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 91
  def _reduce_19( val, _values, result )
 return [:HLine, val[0]]
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 93
  def _reduce_20( val, _values, result )
 return [:SignatureDate, val[0]]
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 95
  def _reduce_21( val, _values, result )
 return [:SignatureName, val[0]]
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 97
  def _reduce_22( val, _values, result )
 return [:SignatureFull, val[0]]
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 108
  def _reduce_23( val, _values, result )
            list = ListAST.new
            list.type = :Bulleted
            list.children << val[1]
            list.children += val[2]
            result = list
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 111
  def _reduce_24( val, _values, result )
 result = []
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 117
  def _reduce_25( val, _values, result )
            result << val[1]
            result += val[2]
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 118
  def _reduce_26( val, _values, result )
 result = []
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 127
  def _reduce_27( val, _values, result )
            li = ListItemAST.new
            li.children += val[1]
            result = li
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 130
  def _reduce_28( val, _values, result )
 result = val[0]
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 134
  def _reduce_29( val, _values, result )
 result = val[1]
   result
  end
.,.,

 def _reduce_none( val, _values, result )
  result
 end

end   # class MediaWikiParser
