#
# DO NOT MODIFY!!!!
# This file is automatically generated by racc 1.4.5
# from racc grammer file "wikimediaparser.y".
#

require 'racc/parser'


class WikiMediaParser < Racc::Parser

module_eval <<'..end wikimediaparser.y modeval..id189d0d9581', 'wikimediaparser.y', 70

attr_accessor :lexer

#Tokenizes input string and parses it.
#--
#TODO: return AST here
#++
def parse(input)
    @yydebug=true
    lexer.tokenize(input)
    return do_parse
end

#Asks the lexer to return the next token.
def next_token
    return @lexer.lex
end
..end wikimediaparser.y modeval..id189d0d9581

##### racc 1.4.5 generates ###

racc_reduce_table = [
 0, 0, :racc_error,
 2, 22, :_reduce_none,
 0, 22, :_reduce_none,
 1, 23, :_reduce_none,
 1, 23, :_reduce_none,
 1, 23, :_reduce_none,
 1, 23, :_reduce_none,
 1, 24, :_reduce_none,
 1, 24, :_reduce_none,
 1, 28, :_reduce_none,
 1, 28, :_reduce_none,
 3, 28, :_reduce_none,
 3, 28, :_reduce_none,
 1, 28, :_reduce_none,
 4, 25, :_reduce_none,
 2, 30, :_reduce_none,
 0, 30, :_reduce_none,
 3, 29, :_reduce_none,
 1, 26, :_reduce_none,
 1, 31, :_reduce_none,
 0, 31, :_reduce_none,
 3, 27, :_reduce_none ]

racc_reduce_n = 22

racc_shift_n = 33

racc_action_table = [
     3,    19,     5,     7,    10,    21,    13,    22,    15,    16,
    17,     2,     5,     7,    10,     9,    13,    23,    15,    16,
    17,     2,    18,    19,    27,     9,    28,    29,    30,    19,
    32 ]

racc_action_check = [
     1,    20,     1,     1,     1,    10,     1,    13,     1,     1,
     1,     1,    19,    19,    19,     1,    19,    15,    19,    19,
    19,    19,     3,     9,    21,    19,    22,    23,    24,    25,
    26 ]

racc_action_pointer = [
   nil,     0,   nil,    22,   nil,   nil,   nil,   nil,   nil,     6,
    -4,   nil,   nil,    -2,   nil,     8,   nil,   nil,   nil,    10,
   -16,    19,    19,    19,    10,    12,    14,   nil,   nil,   nil,
   nil,   nil,   nil ]

racc_action_default = [
    -2,   -22,    -8,   -22,    -1,    -9,    -3,   -10,    -4,   -22,
   -22,    -5,    -6,   -22,    -7,   -22,   -13,   -18,    33,   -22,
   -16,   -22,   -22,   -22,   -22,   -16,   -22,   -11,   -12,   -21,
   -17,   -15,   -14 ]

racc_goto_table = [
     4,    26,    20,     1,   nil,   nil,    31,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    24 ]

racc_goto_check = [
     2,     9,     8,     1,   nil,   nil,     9,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,     2 ]

racc_goto_pointer = [
   nil,     3,    -1,   nil,   nil,   nil,   nil,   nil,    -7,   -19,
   nil ]

racc_goto_default = [
   nil,   nil,   nil,     6,     8,    11,    12,    14,    25,   nil,
   nil ]

racc_token_table = {
 false => 0,
 Object.new => 1,
 :BOLD => 2,
 :ITALIC => 3,
 :LINKSTART => 4,
 :LINKEND => 5,
 :INTLINKSTART => 6,
 :INTLINKEND => 7,
 :SECTION => 8,
 :TEXT => 9,
 :PRE => 10,
 :HLINE => 11,
 :SIGNATURE_NAME => 12,
 :SIGNATURE_DATE => 13,
 :SIGNATURE_FULL => 14,
 :UL_START => 15,
 :UL_END => 16,
 :LI_START => 17,
 :LI_END => 18,
 :OL_START => 19,
 :OL_END => 20 }

racc_use_result_var = true

racc_nt_base = 21

Racc_arg = [
 racc_action_table,
 racc_action_check,
 racc_action_default,
 racc_action_pointer,
 racc_goto_table,
 racc_goto_check,
 racc_goto_default,
 racc_goto_pointer,
 racc_nt_base,
 racc_reduce_table,
 racc_token_table,
 racc_shift_n,
 racc_reduce_n,
 racc_use_result_var ]

Racc_token_to_s_table = [
'$end',
'error',
'BOLD',
'ITALIC',
'LINKSTART',
'LINKEND',
'INTLINKSTART',
'INTLINKEND',
'SECTION',
'TEXT',
'PRE',
'HLINE',
'SIGNATURE_NAME',
'SIGNATURE_DATE',
'SIGNATURE_FULL',
'UL_START',
'UL_END',
'LI_START',
'LI_END',
'OL_START',
'OL_END',
'$start',
'wiki',
'contents',
'paragraph',
'bulleted_list',
'preformatted',
'section',
'element',
'list_item',
'list_contents',
'preformatted_cont']

Racc_debug_parser = true

##### racc system variables end #####

 # reduce 0 omitted

 # reduce 1 omitted

 # reduce 2 omitted

 # reduce 3 omitted

 # reduce 4 omitted

 # reduce 5 omitted

 # reduce 6 omitted

 # reduce 7 omitted

 # reduce 8 omitted

 # reduce 9 omitted

 # reduce 10 omitted

 # reduce 11 omitted

 # reduce 12 omitted

 # reduce 13 omitted

 # reduce 14 omitted

 # reduce 15 omitted

 # reduce 16 omitted

 # reduce 17 omitted

 # reduce 18 omitted

 # reduce 19 omitted

 # reduce 20 omitted

 # reduce 21 omitted

 def _reduce_none( val, _values, result )
  result
 end

end   # class WikiMediaParser
